bazel-ios/rules_ios

- rules/library.bzl
Also, filter out directories that the apple bundling rules choke on
> Use a filegroup for resources

- tools/xcodeproj-shims/xcodeproj-installer.sh
Addresses feedback from https://github.com/ob/rules_ios/pull/21 regarding the xcodeproj-installer.sh script.
> Address feedback from PR 21 for installer script

- .gitignore
> Add Jetbrains .idea file to .gitignore

- rules/library.bzl
- tests/mixed-source/ios/BUILD.bazel
- tests/mixed-source/ios/MixedSourceFramework/Logger/AngleBracketNamespacedLogger.h
- tests/mixed-source/ios/MixedSourceFramework/Logger/AngleBracketNamespacedLogger.m
- tests/mixed-source/ios/MixedSourceFramework/Logger/LoggerProtocol.h
- tests/mixed-source/ios/MixedSourceFramework/Logger/SwiftLogger.swift
- tests/mixed-source/ios/MixedSourceFramework/MixedSourceFramework.h
- tests/mixed-source/ios/MixedSourceTest/ObjCTest.m
* Allow angle bracket imports of -Swift.h headers
* Ensure generated umbrella headers get added to hmaps
* Update tests with new cases
> Mixed module fixes

- docs/hmap_doc.md
- rules/framework.bzl
- rules/hmap.bzl
* Stop generating unused _frame_public_hmap.hmap files
> Some further cleanup of the hmap rules

- rules/hmap/hmap.c
Couldn't leave good enough alone... this code is simpler :-)
> Clean up code in hmap.c

- rules/precompiled_apple_resource_bundle.bzl
- tests/ios/frameworks/core-data-resource-bundle/BUILD.bazel
- tests/ios/frameworks/core-data-resource-bundle/CoreDataExample/CoreDataManager.swift
The coreData example merged in https://github.com/bazel-ios/rules_ios/pull/114 contained some errors
> Fix core data example

- rules/app.bzl
- tests/ios/app/BUILD.bazel
- tests/ios/app/Resources/CustomView.xib
- Add 'resources' to _IOS_APPLICATION_KWARGS
> Allow binaries built with ios_application to include resources

- rules/library.bzl
- tests/ios/frameworks/selectable-deps/BUILD.bazel
> Supports the select method in the deps of apple_library

- docs/app_doc.md
- docs/library_doc.md
- rules/app.bzl
- rules/library.bzl
- rules/library/xcconfig.bzl
- rules/test.bzl
- tests/ios/app/BUILD.bazel
- tests/ios/frameworks/configurable-xcconfig/BUILD.bazel
- tests/macos/xcconfig/BUILD.bazel
- tests/macos/xcconfig/tests.bzl
Add `copts` and `infoplists` behind `select()` statements when 'xcconfig_by_build_setting' and 'infoplists_by_build_setting' are set. For example:
Note 'infoplists' here
```
ios_application(
name = "AppWithConfigurableAttrs",
generator_name = "AppWithConfigurableAttrs",
generator_function = "ios_application",
generator_location = "tests/ios/app/BUILD.bazel:139:16",
bundle_id = "com.example.app",
infoplists = select({"//tests/ios/app:blue": ["//rules/test_host_app:Info.plist", "//tests/ios/app:AppWithConfigurableAttrs.blue.infoplist.0"], "//tests/ios/app:red": ["//rules/test_host_app:Info.plist", "//tests/ios/app:AppWithConfigurableAttrs.red.infoplist.0"], "//conditions:default": ["//rules/test_host_app:Info.plist", "//tests/ios/app:AppWithConfigurableAttrs.infoplist.0"]}), …
```
> Add ability to put xconfig copts behind select() of build settings

- rules/library.bzl
This way, if a macro that calls into `apple_library` needs to provide its own headermaps or something like that, they won't have to leak to targets that depend on the library.
> Allow callers of apple_library to pass in additional private_deps

- rules/repositories.bzl
To pick up https://github.com/bazelbuild/rules_apple/pull/946
> Bump rules_apple

- .github/workflows/tests.yml
This fixes a few unexpected behaviors fixed on v2
> Update github actions checkout

- docs/framework_builder_doc.md
- repository_rules/framework_builder.bzl
I did not actually wire up the value that was being passed it, my mistake 🤦🏻
> Actually wire up `timeout` value for pre-building frameworks

- rules/apple_platform/BUILD.bazel
- rules/library.bzl
Used by https://github.com/bazel-ios/cocoapods-bazel/pull/32
> Allow specifying xcframeworks in calls to apple_library

- rules/xcodeproj.bzl
- tests/ios/xcodeproj/BUILD.bazel
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/xcshareddata/xcschemes/App.xcscheme
Allows users to optionally add an additonal script the be run before
Bazel is run in the generated xcode project
> Adds the ability to specify another prebuild script

- .github/workflows/tests.yml
- BUILD.bazel
- WORKSPACE
Replace the brew dep with Bazel and then pull the version we want.
> Pull buildifier with Bazel

- docs/BUILD.bazel
- docs/app_doc.md
- docs/plists_doc.md
- rules/app.bzl
- rules/plists.bzl
- rules/test.bzl
- tests/ios/unit-test/BUILD.bazel
Enables https://github.com/bazel-ios/cocoapods-bazel/pull/33
> Support dict / selected info plists for tests (in addition to apps)

- .bazelrc
- rules/framework.bzl
- rules/framework/vfs_overlay.bzl
- rules/hmap.bzl
- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
https://github.com/bazelbuild/bazel/issues/10674
I'm sort of stumbling through this due to lack of familiarity, but giving it a shot. Comments inline.
> ObjcProvider compile info => CcCompilationContext

- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tools/xcodeproj_shims/build-wrapper.sh
Specify whether or not to enable exec log and profile from optional xcodeproj attributes. Collect bazel profile and exec log in DerivedData
> Collect exec log, profile from xcodeprojects

- rules/repositories.bzl
Workaround for https://github.com/bazelbuild/rules_swift/issues/640
Fixes https://github.com/bazel-ios/rules_ios/issues/252
> [HOLD] Workaround stderr bug rules_swift

- rules/framework/vfs_overlay.bzl
There are issues when using non absolute-path VFS outside of the
compilation directory, even when setting the `working-directory`. We
can't use absolute paths in this file in Bazel for many reasons. To work
around this, use VFS paths relative to the VFS root via compiler
internals.
Internal to swift and clang - LLVM `VirtualFileSystem` object can
serialize paths relative to the absolute path of the overlay. This
requires the paths are relative to the overlay. While deriving the
in-memory tree roots, it pre-pends the prefix of the `vfsoverlay` path
to each of the entries.
In practice, this is required to use rules_ios vfsoverlay with Xcode's
indexer and SourceKit: e.g. in Bazel Xcode project generators like the
one in rules_ios or XCHammer.
> Use absolute vfs paths via LLVM `VirtualFileSystem`

- rules/xcodeproj.bzl
This PR adds the virtulized framework aruguments for rules_ios into the
xcode proj generator.
The generator needs to behave differently with `virtualize_frameworks`.
It disables the current behavior like copying swift modules and setting
header search paths for LLDB and the indexer.
Note that the PR extends the existing approach rules_ios' took to adding
hmap args. It adds vfs args ( like the other args ) with assumptions
about how rules_ios rules work.
> [xcodeproj] Adds `rules_ios` virtual framework args

- rules/framework.bzl
- rules/library.bzl
fixed Unable to compile xxx.hpp in apple_framework
> fixed Unable to compile xxx.hpp in apple_framework

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/installer
- tools/xcodeproj_shims/install.sh
In the case of VFS it will not build a framework.
> Prevent running install if framework is missing

- rules/framework/vfs_overlay.bzl
Currently root entries in the vfsoverlay are formed with the path
`/build_bazel_rules_ios/frameworks/$FRAMEWORK.framework`. This causes
issues when these vfsoverlays are used within Xcode's indexing system,
and Bazel's dependency pruning code. For instance, a path of a header
would be
`/build_bazel_rules_ios/frameworks/$FRAMEWORK.framework/Headers/Header.h`
as opposed to `$SRCROOT/path/to/Header.h`. In the IDE, this bug can
break jump to definition under some situations and dependency pruning
in Bazel.
The is a longstanding issue in `rules_ios`'s
`rules/framework/vfs_overlay.bzl` rule. It impacts both virtual or non
virtual framework usage of the rule.
By putting the framework in it's own path entry, the `VirtualFileSystem`
correctly serializes the paths.
> [VFS] Nest frameworks in FRAMEWORK_PATH

- tools/xcodeproj_shims/xcodeproj-installer.sh
This is a trick we use, and that we learned from some developers at Lyft, to enable (re-)generating an Xcode project without being prompted to reload Xcode. In other words, this dialogue:
> Enable project generation without reloading the Xcode project

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tools/xcodeproj_shims/installers/_indexstore.sh
Not sure if this is required or not, but since it's embedded in the
index store data, it should be better match with the local one.
> Remap remote developer dir to local developer dir

- BUILD.bazel
- rules/import_middleman.bzl
- rules/library.bzl
- rules/test.bzl
If the deps are within the `test_deps`, don't pass them to the provdider. Fixes
problems when there are duplicate inputs.
> [Apple Silicon] De-duplicate M1 middleman deps

- tools/m1_utils/update_dynamic.sh
- tools/m1_utils/update_static.sh
Remove the M1 util extraction dir on exit
> [Apple Silicon] Cleanup M1 util archive extraction dir

- tools/xcodeproj_shims/output-processor.rb
- https://github.com/bazel-ios/rules_ios/pull/399 - issues with errors not working anymore
> Minor reverts of commits

- tools/xctest_absolute_source_locations/xctest_absolute_source_locations.m
Fixes original code for Xcode 13. Simplify it and leverage that source
URLs are symlinked into the execution root.
> [Xcode 13] Simplify XCTest runtime patch

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tools/xcodeproj_shims/installers/lldb-settings.sh
also address shellcheck linter warnings
> Fix unable to append settings that has new line character in it

- rules/library.bzl
Addresses the FIXME - this causes issues in certian circumstances
> Always set VFS copts in objc_library

- WORKSPACE
- rules/repositories.bzl
- rules/third_party/xcbuildkit_repositories.bzl
- rules/third_party/xcbuildkit_version.bzl
- rules/third_party/xchammer_repositories.bzl
#460 
Copying files here is not ideal but until .bzlmod is ready I don't see a better way to handle this and don't force consumers to update their `WORKSPACE` files to add XCHammer specific `load`s
> Load XCHammer and XCBuildKit deps

- rules/apple_patched.bzl
- rules/framework.bzl
- rules/framework/vfs_overlay.bzl
Plug the documentation bits into the framework.
> Fix IDE documentation popup window

- BUILD.bazel
- rules/features.bzl
- rules/framework.bzl
- rules/framework/vfs_overlay.bzl
In VFS it can't load transitive files from bazel-out
> Add xcode.compile_with_xcode feature

- rules/repositories.bzl
- rules/third_party/xchammer_repositories.bzl
Requires:
* https://github.com/bazel-ios/tulsi/pull/2
* https://github.com/bazel-ios/xchammer/pull/9
> Pick up fix for handling infolists attr separately in XCHammer

- tools/xctest_absolute_source_locations/xctest_absolute_source_locations.m
In Xcode 13.3 XCTFail stoped sending absolute source file paths to
`-[XCTSourceCodeLocation initWithFileURL:lineNumber:]` so reading the
`DO_NOT_BUILD_HERE` from the parent of URL stopped working.
Better, prepend the `info.plist` for the corresponding bundle to the
relative path if it doesn't already exist. On 13.* it works the same.
> [Xcode 13.3] patch `WorkspacePath` onto test failures

- rules/repositories.bzl
- rules/third_party/xchammer_repositories.bzl
Picks up:
* https://github.com/bazel-ios/xchammer/pull/25
* https://github.com/bazel-ios/xchammer/pull/24
* https://github.com/bazel-ios/tulsi/pull/5
> Bump XCHammer and Tulsi

- WORKSPACE
- rules/repositories.bzl
- rules/third_party/xchammer_repositories.bzl
Fixes some lower-level bootstrapping/bazel issues with xchammer and gets rid of some performance issues as well.
> Bump xcbuildkit, tulsi, and xchammer versions to pull in fixes

- tests/ios/frameworks/sources-with-prebuilt-binaries/Gemfile.lock
Addresses https://github.com/bazel-ios/rules_ios/security/dependabot/3
> Bump tzinfo

- rules/precompiled_apple_resource_bundle.bzl
It was missing input manifests and other inputs. Invoke with correct
apple_support convention
> [Buildfarm] Make precompiled bundle compilation hermetic

- rules/test.bzl
- tests/ios/app/BUILD.bazel
- tests/ios/app/empty_tests.m
Required for folks trying to run tests on device
> Add provisioning_profile to test rules

- WORKSPACE
- rules/framework.bzl
- rules/framework/vfs_overlay.bzl
- rules/hmap.bzl
- rules/import_middleman.bzl
- rules/internal/framework_middleman.bzl
- rules/internal/objc_provider_utils.bzl
- rules/legacy_xcodeproj.bzl
- rules/library.bzl
- rules/library/xcconfig.bzl
- rules/precompiled_apple_resource_bundle.bzl
- rules/transition_support.bzl
- tools/toolchains/xcode_configure/BUILD
Too many squiggles when I'm working on stuff, so took a quick cleanup pass.
I'd love to figure out how to suppress errors on the `xcspecs` file and add a bunch more docstrings, but this is a baby step 😄
> Run buildifier fix, clean up unused variables/functions

- rules/import_middleman.bzl
Allows debugging of this error
> Fixes formatting for middleman error

- rules/repositories.bzl
- rules/xcodeproj.bzl
This reverts commit 464a6421665e6c480eabec9ee42382d8f6ecf081.
> Revert "Bump xchammer and xcbuildkit (#597)"

- rules/repositories.bzl
Updates to pull fixes for RBE
https://github.com/bazelbuild/rules_apple/pull/1923
> [LTS][Buildfarm][Remote execution] Bump rules_apple

- tools/tests/prepare_sim.py
CI doesn't want to create simulators very well today, add some retrys and print out the simulators to ensure they're loaded
> [CI][Resiliance] Print sims, add retry

- rules/library.bzl
I'm pretty sure the comments were reversed.
> Fix the comments about angle bracket / double quote imports

- rules/test.bzl
Only merge if https://github.com/bazelbuild/rules_apple/pull/1948 gets merged.
> Forward `bundle_name` to iOS test rules

- tools/compile_only_aspect.bzl
The compile only aspect target would not compile any targets created in `swift_test`. This would lead to green builds when there were in fact build errors.
This fixes it by including `swift_test` as a possible rule kind.
> Fix compile only aspect for swift_test targets

- .bazelrc
- rules/import_middleman.bzl
Fixes https://github.com/bazel-ios/rules_ios/issues/672.
> Enable `--experimental_strict_conflict_checks`

- tools/xcodeproj_shims/ld-stub.sh
Similar to https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/2359
> [Xcode 15] Fix libtool version check

- rules/library.bzl
Make `apple_framework` support swift compiler plugins.
> Support Swift Macro

- rules/repositories.bzl
Pulls Xcodegen 0.19.0 from upstream with rosetta slice
> [xcodeproj] Bumping xcode gen for arm64

- tests/ios/unit-test/test-imports-app/Header2.h
- tests/ios/xcodeproj/fixtures/test_custom_output_path_expected_diff.txt
Stop gaps https://github.com/bazel-ios/rules_ios/issues/830 while it's being root caused.
> Stop gap #830 by using pragma once

- rules/library.bzl
https://github.com/bazelbuild/rules_swift/pull/1162
> Allow consumers to set always_include_developer_search_paths in swift_library

- rules/hmap.bzl
The `HmapCreate` action was not providing the inputs to the action which seems like a potential issue
> Add headers to `headermap` action `inputs`

- rules/precompiled_apple_resource_bundle.bzl
> Select device_families by platform_type in precompiled_apple_resource_bundle
