bazel-ios/rules_ios

- .bazelrc
- .github/workflows/PR.yml
- BUILD.bazel
- WORKSPACE
- docs/hmap_doc.md
- rules/BUILD.bazel
- rules/hmap.bzl
Run `bazel run docs` to generate the docs and move them into `docs/`
> Setup stardoc for documentation of the rules

- docs/framework_doc.md
- rules/framework.bzl
This is helpful for two scenarios, but given the same refactor made both possible they're clumped together:
(a) prebuilt libraries that specify public & private headers can now be packaged as a framework so imports work as expected
and (b) creating a better framework for tests to import their test host, but without double linking issues
> Allow packaging empty frameworks, and skipping certain parts of packaging

- rules/library.bzl
Don't pack them into .framework/PrivateHeaders and don't pass them as a private header to the modulemap builder
This mimics cocoapods' behavior for when both public and private headers are specified explicitly
> Properly handle completely non-exported / "project" headers

- rules/library.bzl
- rules/library/resources.bzl
(not done in the macro so selects can be passed in as resources)
Needed to support https://github.com/ob/cocoapods-bazel/pull/6.
> Use a custom rule for resource filegroups

- rules/library.bzl
- rules/library/resources.bzl
This way, our macros can filter out other directories that are causing clashes at the moment (`.lproj` dirs, I'm looking at you...)
> Allow customizing which resource extensions are filtered

- rules/framework.bzl
- tests/app/ios/BUILD.bazel
Add a test so we dont regress again
Fix is not passing in None as the --framework_root. Since we still need to generate the manifest (since its been declared), simply write it out
> Handle empty frameworks

- rules/framework/framework_packaging.py
- rules/library.bzl
- tests/app/ios/App/main.m
- tests/app/ios/BUILD.bazel
- tests/app/ios/OnlySources/OnlySources.m
Even if there are no headers.
This mirrors CocoaPods’ behavior around when modulemaps are generated (whenever there are any sources), and allows objc frameworks with only `.m`s to be imported (as pointless as that may seem).
Test added to verify behavior change
> Generate modulemaps for frameworks with only ObjC sources

- rules/test.bzl
When visibility is specified in the kwargs of ios_unit_test, it will now get passed as a kwarg to the unit_test rule, not the apple_library rule.
> Pass visibility arg to test rule, not library rule

- .github/workflows/tests.yml
- rules/library.bzl
- tests/swift_version/BUILD.bazel
- tests/swift_version/empty.swift
We need to canonicalize the `swift_version` field to handle version 5.1, as SwiftC only accepts `4`, `4.2` or `5` as valid versions. We have reason to believe that only major versions will be used going forward.
> Handle podspecs that identify their swift_version supported as 5.1

- rules/test.bzl
- tests/test/ios/BUILD.bazel
- tests/test/ios/resource-file.txt
- Pass the `resources` argument from the `rules_ios` `ios_unit_test` macro into the `ios_unit_test` rule vended by `build_bazel/rules_apple`
- Ensure the `resources` argument from the `rules_ios` `ios_unit_test` macro does not get passed along to `swift_library` and `objc_library`
> Add resources to ios_unit_test kwargs

- rules/library.bzl
- tests/mixed-source/ios/BUILD.bazel
- tests/mixed-source/ios/MixedSourceFramework/Logger/DoubleQuoteLogger.h
- tests/mixed-source/ios/MixedSourceFramework/Logger/DoubleQuoteLogger.m
- tests/mixed-source/ios/MixedSourceFramework/Logger/DoubleQuoteNamespacedLogger.h
- tests/mixed-source/ios/MixedSourceFramework/Logger/DoubleQuoteNamespacedLogger.m
- tests/mixed-source/ios/MixedSourceFramework/Logger/SwiftLogger.swift
- tests/mixed-source/ios/MixedSourceFramework/MixedSourceFramework.h
Today when we use the `apple_framework` macro to create a `.framework` everything works fine… unless one of the framework's Objective-C files tries to import a Swift file.  Framework authors who import the framework's generated Swift header in their Objective-C source like so:
`#import "MySpecialFramework/MySpecialFramework-Swift.h`
or 
`#import "MySpecialFramework-Swift.h`
… will see a `clang` error when they try and compile those lines:
`fatal error: 'MySpecialFramework/MySpecialFramework-Swift.h' file not found`
or
`fatal error: 'MySpecialFramework-Swift.h' file not found`
This PR generates an additional header map that allows a framework's Objective-C files to be able to import the generated Swift header with either of the double-quoted `#import` statements listed above.
> Enable Objective-C files in mixed-source frameworks to import the generated Swift header

- rules/library.bzl
- tests/xcconfig/BUILD.bazel
- tests/xcconfig/weak_property.m
Due to a prior refactor, `_prepend_copts` didn't actually prepend to
its parameters, but rather re-assigned.
This PR ensures that the list that gets passed through to the underlying
rules is modified.
This change is tested by adding a library that cannot compile without
the `copts` from its xcconfig applied. ObjC files using manual reference
counting cannot be compiled without the `-fobjc-weak` flag, which in
this case is only applied by the `CLANG_ENABLE_OBJC_WEAK` xcconfig.
> Actually prepend copts so they get passed to tools

- .bazelrc
- docs/hmap_doc.md
- rules/hmap.bzl
- rules/library.bzl
Before, the file in hdrs referred to a non-existant source file
We can see the fix in effect by the xcodeproj build not failing, since the `-Swift.h` header is no longer getting added to the xcode project !
cc @wileykestner
> Refer to actual generated swift header when making swift hmap

- rules/test_host_app/main.m
It was left in accidentally from debugging months ago
The cocoapods-generated app host does not set a background color, so we shouldnt either
> Remove background color from default test host app

- docs/app_doc.md
- docs/library_doc.md
- rules/app.bzl
- rules/library.bzl
- tests/app/ios/App/main.m
- tests/app/ios/BUILD.bazel
- tests/app/ios/infoplist_test.m
This allows specifying entries directly in the BUILD file,
rather than requiring users to write out a plist file themselves
This will allow cocoapods-bazel to emit `app_spec.info_plist`
specifications into BUILD files, keeping the behavior whereby no
files outside of BUILD files need to be written
> Add support for specifying a dict of infoplist values

- docs/hmap_doc.md
- rules/hmap.bzl
- rules/library.bzl
- rules/repositories.bzl
* Remove public hmap propagation
It can only confuse clang, since all public headers are now visible via frameworks
* Update shallow_since for rules_swift
* Fix typo in hmap impl
* Stop quoting the path to hmaps
objc_library already have the quotes stripped, and the extra quotes break swift_library from actually seeing the headermaps
> Fix swift's clang importer being able to see hmaps

- rules/test_host_app/AssetCatalogFixture.xcassets/Contents.json
- rules/test_host_app/BUILD.bazel
- rules/xcodeproj.bzl
- tests/xcodeproj/Single-Application-Project.xcodeproj/project.pbxproj
For xcasset sources, we do not want xcode to run actool. I'm not sure how to stub out the CompileAssetCatalog command, so it's easier to just load xcasset files into the xcodeproject, but not associate them with any build phase.
> Avoid generating a CompileAssetCatalog build phase

- rules/app.bzl
Adding another keyword argument to pass through to `rules_apple`'s `ios_application` rule.
Documented at: https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_application
> Pass 'app_icons' to rules_apple's ios_application

- rules/framework.bzl
- rules/hmap.bzl
- rules/repositories.bzl
- tests/test/ios/test-imports-app/BUILD.bazel
- tests/test/ios/test-imports-app/SomeFramework/Foo.swift
- tests/test/ios/test-imports-app/empty.swift
Since rules_swift is doing a migration from objc provider to ccInfo's compilation context,
we need to match on our side with what they do so build is still successful.
The test added will fail without the addition of CcInfo inside framework.bzl.
Error was: `no such module 'SomeFramework'`
Also point to latest commit on master branch of `rules_swift` and `rules_apple`
> Copy compilation context from objc provider to CcInfo

- .github/workflows/tests.yml
- .vscode/extensions.json
- .vscode/settings.json
- docs/BUILD.bazel
- docs/hmap_doc.md
- docs/library_doc.md
- rules/framework.bzl
- rules/framework/BUILD.bazel
- rules/framework/framework_packaging.py
- rules/hmap.bzl
- rules/hmap/.clang-format
- rules/hmap/BUILD.bazel
- rules/hmap/hmap.c
- rules/hmap/hmapdump.c
- rules/library.bzl
- rules/vfs_overlay/BUILD.bazel
- tests/xcconfig/tests.bzl
This PR standardizes the C formatting using clang-format, and fixes a bunch of errors flagged by buildifier. It also removes some dead code. It is a non-functional change.
I was finishing  #52 but kept mixing up formatting changes with the actual changes so I figured I'd do the cleanups first and then rebase #52 on top of this.
> NFC: Cleanups

- rules/xcodeproj.bzl
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tools/xcodeproj_shims/BUILD.bazel
- tools/xcodeproj_shims/build-wrapper.sh
- tools/xcodeproj_shims/output-processor.rb
- tools/xcodeproj_shims/xcodeproj-installer.sh
This PR changes the xcodeproj Bazel file to include an additional build wrapper that allows us to call an output processor.
The output processor is needed because:
1. Bazel outputs all build progress information to `STDERR`, causing Xcode to think that there was an error building the project.
2. Bazel outputs some of its build progress in a way that Xcode interprets as build error
3. The issue navigator in Xcode doesn't work with the way Bazel outputs the paths for files when building using Bazel. We can post-process each line of output to prepend the full path to `BAZEL_WORKSPACE_ROOT` to correct this.
Finally, developers are able to click an error or warning in the issue navigator and be directed to the corresponding warning / error.
> Adds a build wrapper script for Bazel build processing

- rules/xcodeproj.bzl
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
This PR undoes adding the `test_host` to the list of dependencies in order to prevent it's sources from being included in other target's compile sources build phase.
After discussion with @segiddins and @amberdixon, we considered preventing `_SrcInfo` from being appended to the list of providers, but after testing, that still didn't work.
See PR #46 for original context.
**Before**
**Now**
> Remove test_host from list of deps to avoid including extra sources during compile sources phase

- rules/xcodeproj.bzl
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
This PR adds the suggested patch from @segiddins that allows platform and minimum deployment target to be passed through to target configuration option settings in Xcode.
If the platform is `iOS`, it will add `IPHONEOS_DEPLOYMENT_TARGET` with the corresponding minimum version.
If the platform is `macOS`, it will add `MACOSX_DEPLOYMENT_TARGET` with the corresponding minimum version (and set the `SDKROOT` to `macosx` if needed).
> Adds deployment target configs based on provided platform_type & minimum_os_version

- .gitattributes
- .github/workflows/tests.yml
- rules/repositories.bzl
- rules/xcodeproj.bzl
- tests/macos/xcodeproj/BUILD.bazel
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- tools/xcodeproj_shims/BUILD.bazel
- tools/xcodeproj_shims/IDEWorkspaceChecks.plist
- tools/xcodeproj_shims/xcodeproj-installer.sh
* Mark xcodeproj directories as generated
This way, github will collapse diffs & have more accurate repo stats
* Write all xcodeproj files into the tmp_dest
This way, everything will get chmod’d
This fixes back-to-back runs of the installer failing due to permission issues
* Add a test that verifies that projects can regenerate without error
* Add support for specifying additional (non-srcs) files to be included in the project
This would allow a project to, for example, include a README as a file reference, even though it isnt a src belonging to any particular target
* Download GitHub repos via http_archive
* Add IDEWorkspaceChecks.plist to generated projects
So opening the project in Xcode doesn’t add a new file
* Include BUILD files in generated Xcode projects
* Explicitly opt out of …
> Generated xcodeproj improvements

- rules/xcodeproj.bzl
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tools/xcodeproj_shims/build-wrapper.sh
- tools/xcodeproj_shims/installers/indexstores.sh
Use BEP to determine which indexstore paths were generated by the compilation steps of the build. Only move those over, so we don't move every generated indexstore. This was a suggestion from other engineers at ios-dev-at-scale to make index remapping more efficient.
> Only move indexstores generated by build

- .github/workflows/tests.yml
- rules/library.bzl
- tests/macos/xcodeproj/BUILD.bazel
This behavior is similar to swift_library: https://github.com/bazelbuild/rules_swift/blob/master/swift/internal/derived_files.bzl#L66 (See its invocation of `actions.declare_directory` from `_indexstore_directory`.)
We observed an issue where it took a long time for index-import to remap bazel-generated indexstores. The slowdown was actually a result of the fact that all objective-c indexstores were being placed in the same .indexstore directory. When we broke them apart by objective-c library, things got considerably faster. Before these changes, it took 3 minutes to remap for a larger project, but now it takes 3 seconds.
There is an alternative approach we can take. This approach has been taken by Brentley here: https://github.com/lyft/index-import/pull/46 This PR is open right now, but …
> Separate objective-c indexstore units and records by objc_library

- rules/xcodeproj.bzl
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tools/xcodeproj_shims/build-wrapper.sh
- tools/xcodeproj_shims/install.sh
- tools/xcodeproj_shims/installers/indexstores.sh
I considered using something like this build setting: https://pewpewthespells.com/blog/buildsettings.html#derived_file_dir
But I changed my mind, because I thought it might be easier to find the `bazel-xcode-diagnostics` directory if it was sitting closer to the root. Let me know if there are some other reasons I should consider using a deeper subdirectory of the derived data for the project.
> Collect diagnostics about indexing so we can debug problems more easily

- rules/xcodeproj.bzl
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
When generating and building a Bazel-generated project after launching with: 
```sh
bundle exec bazel run <The-Xcode-Project>
bundle exec xed The-Xcode-Project.xcodeproj
```
The Xcode Bazel build shim is carried into the parent environment which prevents the build from executing:
```bash
Showing Recent Messages
+ /Users/ndizazzo/Development/ios/register/bazel-scratch/CXF-Project.xcodeproj/bazelstubs/output-processor.rb
/Users/ndizazzo/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize': Could not find json-1.8.6 in any of the sources (Bundler::GemNotFound) from   
/Users/ndizazzo/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:85:in `map!' from /Users/ndizazzo/.rvm/rubies/ruby-2.6.1/lib/ruby/site_ruby/2.6.0/bundler/spec_set.r …
```
> Invokes the Bazel build shim script unsetting Ruby environment variables beforehand

- rules/library.bzl
Now clang/swiftc will no longer embed PCM absolute paths in object files
> Make swift & objc object files cachable

- rules/library/xcconfig.bzl
- tests/ios/frameworks/target-xib/BUILD.bazel
- tests/macos/xcconfig/BUILD.bazel
- tests/macos/xcconfig/tests.bzl
obj_library and cc_library shell-expand their copts & linkopts, swift_library does not
> Handle bourne shell tokenization in objc_copts and linkopts when expanding xcconfigs

- rules/library/resources.bzl
They bloat the size of the bundles and serve no purpose, since the compiled Assets.car is already in the bundle
> Stop copying xcasset directories into compiled resource bundles

- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/indexstores.sh
- tools/xcodeproj_shims/installers/indexstores.sh
The bazel build process generates indexstores, if the necessary index-store-path options are enabled.
The xcodeproject invokes bazel build. Then it moves the generated indexstores to the derived data directory. This fixes a bug where only the FIRST indexstore was getting moved and not the others!!!!
> Unique the list of indexstores and move all of them, not just the first

- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/installer
- tools/xcodeproj_shims/install.sh
This experimental setting has been around for 2+ years, and allows rules_apple to skip the zip archive when creating bundles, saving significantly on space used
See https://github.com/bazelbuild/rules_apple/issues/49
Also ran shellcheck over the script, and corrected the warnings (by quoting :all-the-things:)
> Allow defining apple.experimental.tree_artifact_outputs when building xcodeprojs

- rules/hmap/hmap.c
Don't assume doubling the buffer once makes it big enough
> Fix a memory error in hmaptool

- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/NonArcObject.h
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
For some reason instead of generating dwarf only for debug config, by default xcodeGen is specifying to generate dwarf+dSYM for all configs. Generating dsym file can take a long time for big targets, so it's time saving to disable it for now
Also we are seeing lots of warnings from `dsymutil` regarding `swiftmodule` files not found. This will turn off this warnings as well
1. Fix an error during testing regarding NonArcObj not having NSObject as super class
> Disable generation of debug info (dSYM) file by default for all xcode projects

- .bazelrc
- rules/BUILD.bazel
- rules/app.bzl
- rules/library.bzl
- rules/test.bzl
- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/build.sh
- tools/xcodeproj_shims/build-wrapper.sh
Only do this if local_debug_options_enabled is specified at command line. Make xcode specify this config.
The changes in this PR are taken from the suggested changes in https://github.com/ios-bazel-users/ios-bazel-users/blob/master/DebuggableRemoteSwift.md to get debugging working.
Note that in order for the example applications and tests in the rules_ios repo to be debuggable from Xcode, you must:
1. Disable sandboxing in .bazelrc.
2. Update the flag in the tools/xcodeproj_shims/build-wrapper.sh to refer to `--//rules:local_debug_options_enabled` rather than `--@build_bazel_rules_ios//rules:local_debug_options_enabled`
There are still known issues with evaluating variables from the debugger for swift tests.
> Add local debug options as a dependency, but only if local_debug_options_enabled

- rules/repositories.bzl
Since the rules_apple we point via the commit has pointed to xctestrunner 0.2.13, which contains fix for pointing to explicit python 2.7 version (instead of just py2), we should be able to go ahead and unpin the xctestrunner version.
This is just part 1 because the rules_apple we point to is not the latest, what is blocking this is a new migration from `whitelist_function_transition` to `allow_list_transition` that is under `bazel_tools`: see this commit: https://github.com/bazelbuild/rules_apple/commit/c283c82941e9f7e58f5176b68850e6a91b68e956
Existing tests is enough, also tested against downstream projects
try to point to latest commit of rules_apple, this means we need to bump bazel version. This will be coordinated in future ticket.
> Bump rules apple part 1: unpin xctestrunner

- .bazelrc
- .github/workflows/tests.yml
- rules/transition_support.bzl
- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/build.sh
- tests/ios/xcodeproj/post_build_check.sh
- tests/ios/xcodeproj/pre_build_check.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tools/xcodeproj_shims/build-wrapper.sh
With the change introduced in https://github.com/bazel-ios/rules_ios/pull/98, when bazel builds behind the scene (inside 1build-wrapper1), it will generates one that enables swift to be debuggable. However the framework search paths generated during the xcodeproj generation stage (`bazel run some_xcodeprojec_rule`) will generate a different configuration cache than the one generated by bazel build (since inside build wrapper there are additional flags: 1. compilation mode and 2. local_debug_option)
As evidenced by the test fixture changes, the search paths are changed in this PR because 
1. 1compilation_mode1 is set to debug to match with when xcode builds under debug config (not release config, so under release this is still broken)
2. `local_debug_option` is set to True for both xcode …
> Force swift local debug option to be turned on so that framework search path has correct payload after project is built

- rules/xcodeproj.bzl
- tests/ios/unit-test/test-imports-app/BUILD.bazel
- tests/ios/xcodeproj/BUILD.bazel
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/xcshareddata/xcschemes/SomeFramework.xcscheme
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/xcshareddata/xcschemes/TestImports-App.xcscheme
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/xcshareddata/xcschemes/TestImports-Unit-Tests.xcscheme
- tests/ios/xcodeproj/build.sh
- tests/ios/xcodeproj/post_build_check.sh
- tests/ios/xcodeproj/pre_build_check.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/xcshareddata/xcschemes/TestImports-App.xcscheme
Due to the need to have a "framework_unlinked" version of a app so that tests can run, we end up having a framework target with name `Foo` while there is an app target also with name `Foo`. If we don't ignore one of them, during `xcodeproj` generation phase one will overwrite the other.
This PR is therefore putting efforts to prevent this from happening:
1. a new tag so dev can specify to ignore one of them
2. a check to prevent such thing from happening
The new xcodeproj rule is testing against above situation so without the tag, new test cases will fail during `bazel run <some_xcodeproj_rule>` stage
1. Where to document this new tag?
> New tag to help ignore targets, also checks to make sure no target overwrite with different type

- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tools/xcodeproj_shims/build-wrapper.sh
Execution log file from bazel can eat a lot of disk space and is not useful when builds are working.
Only when it is not working, where engineer can ask the end user of this repo to change the `BAZEL_EXECUTION_LOG_ENABLED` inside xcode to 1 (at the highest level possible, usually project level) so that during bazel build, the execution log will be dumped to the specified path
no test since it can be easily verified manually.
High, as it impacts dev's disk space
Should I document this user defined flag inside xcodeproj somewhere?
> Added a flag to disable logging of execution log from Bazel by default

- rules/library/resources.bzl
- rules/repositories.bzl
- rules/xcodeproj.bzl
- tests/ios/unit-test/test-imports-app/BUILD.bazel
- tests/ios/unit-test/test-imports-app/Resources/TestModel.xcdatamodel/contents
- tests/ios/unit-test/test-imports-app/Resources/TestModel2.xcdatamodel/contents
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
If one revert just the changes in xcodeproj.bzl and regenerate the newly added "Simple-iOS-App-Project" target under bazel and open the `Simple-iOS-App-Project.xcodeproj`, you will see that the .xcdatamodel or .xcdatamodeld is not presented correctly under the project:
This change simply detect such special directory and choose to only add the directory itself (nothing underneath) so that XCode will present the, correctly (see screenshots). The current version feature for data model is also tested in this PR.
Also updated to latest version of xcodegen to pick up latest improvements
Not concrete test on whether the project will compile and read datamodel. Also we for sure knows that just adding the xcdatamodel to xcode directly won't work as bazel side does not pick that up.
Before:
After:
> Fix how xcdatamodel is represented under generated xcodeproj 

- rules/framework/framework_packaging.py
(a) this saves a libtool invocation
(b) it ensures that input & output can share storage in the CAS cache (as e.g. libtool might change the timestamp due to -D, which isn’t present for ld invocations in all versions of the c++ crosstool)
> Copy when “merging” a single binary

- docs/precompiled_apple_resource_bundle_doc.md
- rules/precompiled_apple_resource_bundle.bzl
- tests/ios/frameworks/core-data-resource-bundle/BUILD.bazel
- tests/ios/frameworks/core-data-resource-bundle/CoreDataExample/CoreDataManager.swift
- tests/ios/frameworks/core-data-resource-bundle/CoreDataExample/Model.xcdatamodeld/Model.xcdatamodel/contents
- tests/ios/frameworks/core-data-resource-bundle/CoreDataExample/Person.swift
- tests/ios/frameworks/core-data-resource-bundle/CoreDataExampleTests/CoreDataExampleTests.swift
- tests/ios/frameworks/target-xib-resource-bundle/BUILD.bazel
- tests/ios/frameworks/target-xib-resource-bundle/TargetXIB/CustomView.swift
- tests/ios/frameworks/target-xib-resource-bundle/TargetXIB/CustomView.xib
- tests/ios/frameworks/target-xib-resource-bundle/TargetXIBTests/CustomViewTests.swift
Fixes https://github.com/bazel-ios/rules_ios/issues/113
I couldnt find a way to properly pass the `swift_module` parameter to the `xibCompile` step, so instead I changed the label for the `fake_ctx` (which seems to be non important) to match the required `swift_module`: in the end, such label is used as a fallback value when `swift_module` is not specified.
You can see the fallback here: https://github.com/bazelbuild/rules_apple/blob/master/apple/internal/partials/support/resources_support.bzl#L446
> Fix the precompiled_apple_resource_bundle to use a correct swift module

- rules/xcodeproj.bzl
- tests/ios/unit-test/BUILD.bazel
- tests/ios/xcodeproj/BUILD.bazel
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/xcshareddata/xcschemes/ExplicitHosted.xcscheme
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/xcshareddata/xcschemes/iOS-9.3-AppHost.xcscheme
Fix xcodeproj: 
* Pass a custom name correctly
* Add the host app to the project when adding the transitive dependencies (seems it was forgotten)
> Some fixes to the xcodeproj rule

- .bazelrc
- README.md
- rules/framework.bzl
- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/build.sh
- tests/ios/xcodeproj/post_build_check.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tools/xcodeproj_shims/installers/lldb-settings.sh
Debugging apps and tests with transitive swift when `cacheable_swiftmodules` was enabled was not working for us, because:
1. the LLDB swift-extra-clang-flags setting was not set, and
2. Frameworks that generated ASTs were not propagating the appropriate linker options to apps/tests that depended on them. `link_inputs` is a critical piece to propagate forward to the linker; according to the documentation (https://docs.bazel.build/versions/master/skylark/lib/ObjcProvider.html#link_inputs): "Link time artifacts from dependencies that do not fall into any other category such as libraries or archives. This catch-all provides a way to add arbitrary data (e.g. Swift AST files) to the linker. The rule that adds these is also responsible to add the necessary linker flags to 'linkopt'."
Note that …
> Set clang flags in lldb, propagate linker options

- rules/repositories.bzl
- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
Xcodegen can now intuit groups properly for paths that start with .., and are above the current directly on disk
(thanks to https://github.com/yonaskolb/XcodeGen/pull/892).
Pointing to my fork for now, since there hasn't been a recent release
> Stop specifiying a manual group for xcodeproj sources

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tools/xcodeproj_shims/installers/lldb-settings.sh
This is important for lldb debugger to work correctly according to https://lldb.llvm.org/use/remote.html#id6
In future we can ask developers to run `platform status` inside lldb to ensure some metadata is correct.
Without this change, do `platform shell pwd` in lldb says `/` and after this it becomes whatever workspace you are actually in.
This might be a solution to some past/existing issues related to lldb debugger.
Testing against downstream project to make sure this works.
> Setting cwd explicitly to ensure lldb remote debugging works on relative paths in debug info etc.

- tools/xcodeproj_shims/xcodeproj-installer.sh
It does not have a trailing slash, since the path was ../../..;
Fixes a regression in https://github.com/bazel-ios/rules_ios/pull/125
> Correctly fix the path of the workspace root group when installing xcodeproj into root

- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- We found that letting this enabled by default causes some header import problems (`foo header not found`) during source indexing, because having this added a compiler option `-I<path_to_hmap_under_derived_source>` for clang invocation, resulting in a different behavior than Bazel (Bazel will never use anything under Derived data for compiling)
No red-green test case found under rules_ios as no testing project is complicated enough that having this setting changed makes a difference for header search.
Testing against downstream project that uses this change did help fix some header import problem, and not making things worse (we have an existing existing test set)
> Disable use headermap on xcode side

- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
In our codebase, we typically have a dependency graph for test suites that looks like this:
TestSuite -> Test_iPad -> Test.__internal__.test-bundle -> TestLibrary_objc
The source files and hmaps for the test code are associated with TestLibrary_objc. The other targets are wrappers that are packaging up this library and possibly other targets. The wrappers need to get associated with the source files for all their direct dependencies (which is why the SrcsInfo provider for wrappers already points to info.srcs, which pulls in dependencies' source files.)
Hmap paths needs to get associated with wrapper targets in the same way. In order for xcode's indexer to be able to compile source files for a target, it needs the correct set of header search paths.
> Associate hmap_paths with wrapper targets in the same way as srcs.

- rules/app.bzl
Passes the `provisioning_profile` argument through to [rules_apple's `ios_application`](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_application).
(We've been adding these as we've needed them, happy to do a more thorough review of all of the `attr`s that we may need to cut down on PR noise if that is preferable.)
> Add provisioning_profile to ios_application kwargs

- rules/xcodeproj.bzl
- tools/xcodeproj_shims/xcodeproj-installer.sh
The swiftc stub depends on the print_json_leaf_nodes python script. This script needs its runfiles to be present in the same directory. Currently, the swiftc-stub commands are failing. On Xcode's old build system, this does not cause the overall build to fail, but on the new build system, it will.
> Add python script runfiles to the xcodeproj directory

- WORKSPACE
- repository_rules/framework_builder.bzl
- tests/ios/frameworks/sources-with-prebuilt-binaries/BUILD.bazel
- tests/ios/frameworks/sources-with-prebuilt-binaries/MixedSourceFramework/Framework.swift
- tests/ios/frameworks/sources-with-prebuilt-binaries/MixedSourceFrameworkTests/Tests.swift
- tests/ios/frameworks/sources-with-prebuilt-binaries/Podfile
Fixes https://github.com/bazel-ios/rules_ios/pull/126
In this PR:
* Added support for vendored frameworks to the build_cocoapods_frameworks repository rule: now find all frameworks recursively under `Pods/_Prebuild/GeneratedFrameworks`. Also added tests
* Refactor code to a simpler implementation
> Added support for vendored frameworks to the build_cocoapods_frameworks repository rule

- rules/framework.bzl
Framework directories for frameworks with swift code need to include (1) a header that bridges Swift <-> Objc (i.e. a FWName-Swift.h file) and (2) a modulemap. The framework packaging rule packages the public and private headers and the modulemap in the final FW package. However, these files were not showing up in the `.framework` directory that is under bazel-out. Returning these fields in the provider fixes the problem.
You can repro the problem and verify that this PR solves it by running `bazelisk build tests/ios/unit-test/test-imports-app:SomeFramework`. After that, run `ls -lR bazel-out/applebin_ios-ios_x86_64-dbg-ST-5dc50b810145/bin/tests/ios/unit-test/test-imports-app/SomeFramework/SomeFramework.framework` to see the contents of the final framework package. In the broken case, …
> Include header files and modulemap for framework packaging in the DefaultInfo provider

- rules/app.bzl
- tests/ios/app/BUILD.bazel
- tests/ios/extensions/BUILD.bazel
- tests/ios/extensions/ExampleExtension/Info.plist
Add `extensions` keyword argument to this list of argument names that are forwarded on to the `ios_application` rule from `rules_apple`.
> Pass "extensions" keyword argument to ios_application from rules_apple

- rules/apple_patched.bzl
- rules/repositories.bzl
It appears this import has moved in a newer version of rules_apple
> Fix error when importing AppleFrameworkImportInfo

- rules/library/xcconfig.bzl
Tried to ignore `ENABLE_BITCODE` instead but it does not work, wonder why...
Tested against downstream project and it now makes Bazel build green
> Ignore settings for bitcode generation as it is controlled by a flag under Bazel

- rules/apple_patched.bzl
Small bugfix to patched apple_static_framework_import: use pop instead of get when extracting the tags attribute from the kwargs
> Small bugfix to patched apple_static_framework_import

- rules/xcodeproj.bzl
- tests/ios/xcodeproj/BUILD.bazel
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
Need to provide a way to insert custom attributes for downstream projects
Was thinking about using a `project_overrides` where one can pass `{'attributes': {key: value}, 'options': {key: value}, 'settings' {key: value}}` to cover other fields that we have default values for. But according to Bazel doc https://docs.bazel.build/versions/master/skylark/lib/attr.html#string_dict values for `string_dict` can only be string, so have to break them up into individual fields like the change proposed here.
Please let me know if there is a better way so that we can allow customization done easily for downstream projects.
After adding one to a sample project, it indeed gets reflected in the corresponding generated project
> Add an entry point to xcodeproj rule for overriding project attributes

- rules/xcodeproj.bzl
- tests/ios/unit-test/test-imports-app/BUILD.bazel
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
Xcode depends on TARGETED_DEVICE_FAMILY to configure the target device types.
> Configures TARGETED_DEVICE_FAMILY for targets in xcodeproj

- rules/framework.bzl
- rules/repositories.bzl
- rules/xcodeproj.bzl
I'm testing the `xcodeproj` rule in our project and since we're on a newer version of `rules_apple` that removed the already deprecated `direct_swiftmodules`, the `xcodeproj` rule would fail. I fixed this and tested it in a Swift project of ours, and it worked.
I understand that `rules_apple` is creating releases every now and then, so I'm not sure if you'd like to follow that release cadence, or you would be fine with following a commit more at HEAD.
I'm happy to hear your thoughts here.
> Bump rules_apple and fix deprecated `direct_swiftmodules`

- rules/app.bzl
If `entitlements_validation` is set pop it to avoid passing it down to `apple_library` where it shouldn't be used.
> Handle entitlements_validation if set

- tests/ios/unit-test/test-imports-app/BUILD.bazel
- tests/ios/unit-test/test-imports-app/Header2.h
- tests/ios/unit-test/test-imports-app/TestImports-App-Bridging-Header.h
- tests/ios/unit-test/test-imports-app/TestImports-Unit-Tests-Bridging-Header.h
- tests/ios/unit-test/test-imports-app/test.swift
- tests/ios/unit-test/test-imports-app/testhelper.h
- tests/ios/unit-test/test-imports-app/testhelper.m
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
Expands the TestImportsApp to include a bridging header
> Add bridging header to TestImportsApp unit tests

- rules/xcodeproj.bzl
- tests/ios/xcodeproj/BUILD.bazel
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tools/xcodeproj_shims/build-wrapper.sh
(See discussion in #171) Adds the ability to pass build configurations to the `xcodeproj` rule.
It's now possible to specify `configs` in the `xcodeproj` rule. Each entry will be created as an Xcode build configuration and append a `--config=$CONFIGURATION` to the underlying bazel invocation.
The `xcodegen` tool requires at least one `debug` and `release` configs so they're added by default if not present. We could simply not set this option in `xcodegen` but then a user would have to know which build setting to change in Xcode to change to a different build configuration. So IMO it's a good trade off having to give `xcodegen` what it needs (without any additional underlying consequence) to create a better UX.
**OLD DESCRIPTION FOR REFERENCE ONLY BELOW**:
The idea is that one can set …
> Add ability to match bazelrc and Xcode build configurations

- rules/app.bzl
Allows users to use the `strings` attribute on `ios_application` rules
> Add `strings` attribute to ios_application

- repository_rules/framework_builder.bzl
Allows users to up the 600 second timeout for prebuilding frameworks via
a `timeout` argument
> Allow users to set prebuild frameworks timeout

- rules/framework.bzl
We get the following error when building a framework and collecting its code coverage:
```
/testing/apple_test_rule_support.bzl", line 83, column 38, in _coverage_files_aspect_impl
covered_binaries = depset(
Error in depset: depsets cannot contain items of type 'list'
ERROR: Analysis of target '//tests/ios/frameworks/target-xib:TargetXIBTests' failed; build aborted: Analysis of target '//tests/ios/frameworks/target-xib:TargetXIB' failed
```
How to reproduce:
Running the next command in this repo:
```bazelisk coverage --experimental_use_llvm_covmap --test_env=LCOV_MERGER=/usr/bin/true //tests/ios/...```
AppleBundleInfo from rules_apple expects a File instead of a list, we pass the first element of binary_out if it exists to solve the problem. …
> Fix bazel coverage binary parameter

- rules/framework.bzl
- rules/framework/framework_packaging.py
So "jump to definition" jumps to the file under the generated Xcode project instead of the one in `bazel-out`
> Symlink headers and modulemap instead of copy in framework_packaging

- rules/library.bzl
Requires unreleased features in bazel to select against
> Ignore maccatalyst slices in xcframeworks

- rules/framework.bzl
- rules/framework/framework_packaging.py
We previously symlink both headers and module_map which don't depend on the clean action to delete stale files.
When compiling objc files depending on the current framework, the framework might have stale header files, which will cause the compilation failure.
Instead of symlinking module_map, we run the framework_packaging action for the module_map (which copies the file). It depends on the clean action and will trigger it.
As module_map is part of the the objc_provider, the framework_packaging action must be triggered before compiling downstream objc files.
1. Instead of using actions.symlink, I tried to manually create the symlink in framework_packaging.py. But build fails with error as bazel failed to cache the dangling symlink.
2. Added the binary to the objc_provider as …
> Ensures the deletion of stale files in non-sandboxed mode

- docs/index_while_building.md
Overall architecture of design for "Index While Building" in Bazel
- https://github.com/lyft/index-import/pull/53
- https://github.com/bazelbuild/rules_swift/pull/567
- https://github.com/bazelbuild/rules_swift/issues/561
> Writeup doc on Index While Building

- rules/app.bzl
Additional icons were added to `rules_ios` in this PR https://github.com/bazelbuild/rules_apple/pull/1032 . This change allows users to use this new feature when using `rules_ios`
> Additional icons support in iOS_application rule

- .bazelrc
- BUILD.bazel
- rules/library.bzl
- rules/repositories.bzl
- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tools/xcodeproj_shims/installers/_indexstore.sh
This concludes the first step of mitigating perf issues and first PR in
the series for index while building - docs/index_while_building.md.
Hinging on the feature, swift.index_while_building_v2, it moves
rules_ios to use a global index and pulls in the swift PR
https://github.com/bazelbuild/rules_swift/pull/567, and index-import PR
https://github.com/lyft/index-import/pull/53 .
In hopes of mitigating performance problems of processing the global
index in this way it flips the `-incremental` bit.
Longer term we will not be processing a global index, per
docs/index_while_building.md so this is temporary measure.
This PR implements line items from 'Index while building V2 - first
pass' in the roadmap for this feature defined in
docs/index_while_building.md.
> Implement 'first pass' of index while building V2

- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tools/xcodeproj_shims/installers/lldb-settings.sh
Can be considered a continuation of #218, now that LLDB is aware of the `FRAMEWORK_SEARCH_PATHS` some use cases might have to be handled case-by-case.
This PR is an example, an objc interface was hidden behind a `#if DEBUG` statement and debugging a `.swift` file that depends on it was failing to find it.
With this change we'll respect the `Debug` config and pass the respective flag to LLDB. Moving forward once we evolve how different build configurations are set/handled we have to remember to take that into consideration in how to pass flags to LLDB. Added comments in two different places about this to ensure it's being called out explicitly.
> Conditionally pass DEBUG flag to LLDB

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tools/xcodeproj_shims/installers/lldb-settings.sh
Continuation of the debugger fixes.
After generating an Xcode project using the `xcodeproj` rule, if different targets are manually built in Xcode it will create paths under DerivedData that can cause LLDB to fail to load it's ASTs since the correct headers and symlinks are being created under `bazel-out` instead. 
If DerivedData is one of the framework search paths for LLDB it will search there and fail before finding the correct paths under `bazel-out` so this PR is explicitly filtering out those paths only for the `target.swift-extra-clang-flags` lldb flag.
> Filter out DerivedData paths before passing FRAMEWORK_SEARCH_PATHS to LLDB

- rules/library.bzl
Let me know if there's a more wholistic Bazel way to reference these types of excluded macOS files. `.DS_Store` files were causing different action keys across machines.
> Exclude .DS_Store in XCFramework slice glob

- rules/xcodeproj.bzl
- tests/ios/app/test_true.mm
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
When building a C++ file, setting LD in Xcode doesn't stub out the
linker, it's a different codepath.
This is a simple way to point at the stub by relying on a public clang
flag `-fuse-ld` Ideally we can replace the full build system without
stubbing out tools e.g. with something like XCBuildKit longer term.
Fixes #228
> Point Xcode at LD stub

- rules/framework.bzl
According to https://github.com/bazelbuild/bazel/issues/10674, the old `define` field on the ObjcProvider is now the `defines` field on CompilationContext.
Related to https://github.com/bazel-ios/rules_ios/pull/199/files
> The defines field should be populated from the deps compilation_context

- rules/xcodeproj.bzl
The stub is useful to emulate IDE quality-of-life improvements such as
showing the app icon in Schemes and target lists.
```python
infoplist_stub = "//App:Xcode.Info.plist"
```
Where **Xcode.Info.plist** contains **CFBundleIconFIle** tailored for the generated project, but will not be built with the app itself.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>CFBundleIconFile</key>
<string>App/Resource/AppIcon.xcassets/AppIcon.appiconset/Icon-80.png</string>
</dict>
</plist>
```
> Make _infoplist_stub public

- rules/test.bzl
add flaky to test arg list so it ends up in tests and not libs, per #243
> [tests]: support flaky kwarg for tests

- rules/additional_scheme_info.bzl
- rules/xcodeproj.bzl
- tests/ios/xcodeproj/BUILD.bazel
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/xcshareddata/xcschemes/ObjcFramework.xcscheme
- tests/ios/xcodeproj/tests.sh
A convention many projects utilize is to have test
targets run as a test action for a scheme where the build
target is not itself a test target, including the
default project generated in Xcode.
MyFramework <-- framework
MyFrameworkTests <-- bundle.unittests
This hopes to enable adding test targets and environment
variables to schemes created for any build target.
> Enable test action associations in schemes

- rules/library/xcconfig.bzl
If we do not copy this array the user will see the following
error when they use `fetch_default_xcconfig`
```terminal
ERROR: Traceback (most recent call last):
File “Something/BUILD", line 242, column 16, in <toplevel>
apple_framework(
File "/private/var/tmp/_bazel_maxwellelliott/db37ab0e01ac1d9a8e5ea282dd04a720/external/build_bazel_rules_ios/rules/framework.bzl", line 26, column 28, in apple_framework
library = apple_library(name = name, **kwargs)
File "/private/var/tmp/_bazel_maxwellelliott/db37ab0e01ac1d9a8e5ea282dd04a720/external/build_bazel_rules_ios/rules/library.bzl", line 401, column 66, in apple_library
copts_by_build_setting = copts_by_build_setting_with_defaults(xcconfig, fetch_default_xcconfig, xcconfig_by_build_setting)
File …
```
> Fixes a frozen dict error in xcconfig logic

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tools/xcodeproj_shims/installers/swiftmodules.sh
Small thing I noticed when debugging the diagnostics output while noticing swift modules never seemed to be found/copied.
```bash
Start copying swiftmodules at Mon Jun  7 11:47:49 CDT 2021
Found 0 existing SWIFTMODULES
No SWIFTMODULES found
Finish copying swiftmodules at Mon Jun  7 11:47:49 CDT 2021
```
This removes a trailing double-quote from the BEP parsing. 
i.e.
```
/private/var/tmp/_bazel_ekerber/dd323d2a4ff53820c11ccc0d5aebe791/execroot/myapp/bazel-out/ios-x86_64-min12.2-applebin_ios-ios_x86_64-dbg-ST-fc18f8f88e01/bin/MyApp.swiftmodule"
```
Which would then fail the -f check in **_swiftmodules.sh**
With this change, swift modules are copied:
```
Start copying swiftmodules at Mon Jun  7 11:56:28 CDT 2021
Found 104 existing SWIFTMODULES
```
> Fix trailing doublequote in swiftmodule installer

- rules/repositories.bzl
To pick up https://github.com/bazelbuild/rules_apple/pull/1181
> Bump rules_apple to pick up smartcard identities support

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/lldb-settings.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/lldb-settings.sh
- tools/xcodeproj_shims/installers/lldb-settings.sh
Can be seen as a continuation of https://github.com/bazel-ios/rules_ios/pull/213
Realized that we also need to include the `HEADER_SEARCH_PATHS` otherwise LLDB won't find the `.hmap` files created in `rules_ios`.
One use case that is broken because of this is debugging a `.swift` file in a test host app that depends on a bridging header (`SWIFT_OBJC_BRIDGING_HEADER ` Xcode setting) and that is `#import`-ing some other headers. Those headers will be added to an `.hmap` file and linked in Xcode's `HEADER_SEARCH_PATHS` setting but as of now LLDB is not aware of it.
> Pass HEADER_SEARCH_PATHS to LLDB

- rules/test_host_app/BUILD.bazel
- rules/test_host_app/test_host_app.bzl
So a consumer of `rules_ios` can optionally initialize the default test host apps with additional attributes.
One example of a use case enabled by this PR is wanting to `bazel run` a [xcodeproj](https://github.com/bazel-ios/rules_ios/blob/master/rules/xcodeproj.bzl#L857) target with the `--ios_multi_cpus=arm64` flag set so the generated Xcode project has `arm64` paths under `bazel-out` for `HEADER_SEARCH_PATHS` and `FRAMEWORK_SEARCH_PATHS` [allowing one to debug .swift sources in mixed projects on device](https://github.com/bazel-ios/rules_ios/blob/master/tools/xcodeproj_shims/installers/lldb-settings.sh#L37-L55).
At this time the above is not possible because `--ios_multi_cpus=arm64` requires a `provisioning_profile` attribute in `ios_application` so it's not possible to use the current …
> Allow test_host_app app rules to receive custom attributes

- rules/precompiled_apple_resource_bundle.bzl
- rules/repositories.bzl
Pickes the fix for propagating swift linker flags in rules_apple: https://github.com/bazelbuild/rules_apple/pull/1186/files
Removes the rules_swift override since the global index store cache is in 0.23.0 now.
> Bumps rules_apple and rules_swift

- data/xcspecs.bzl
- rules/app.bzl
- rules/library/xcconfig.bzl
- rules/precompiled_apple_resource_bundle.bzl
- rules/repositories.bzl
It adds the ability to set `minimum_deployment_os_version` and pulls in
the latest sha of `rules_apple`.
It stopgaps target specific evaluation xcconfig issues. When I tried to
build an app with target specifc xcconfigs with settings like
`SWIFT_PLATFORM_TARGET_PREFIX`, I end up getting invalid `-target` flags
in compiler invocations which were incomplete. `rules_ios`'s xcconfig
evaluator is not a full implementation of xcconfig and conflicts with
Bazel's settings here. It doesn't currently evaluate on a per architecture
basis but aligning the 2 may be a longer term exercise.
This PR is related to #225 : making it a bit easier to align with what Xcode is doing
> minimum_deployment_os_version / `-target` stopgap

- rules/xcodeproj.bzl
- tools/xcode_version_computation/BUILD.bazel
- tools/xcode_version_computation/main.swift
- tools/xcodeproj_shims/BUILD.bazel
- tools/xcodeproj_shims/build-wrapper.sh
- tools/xcodeproj_shims/xcodeproj-installer.sh
When running under Xcode, `rules_ios`'s "build wrapper" currently
overrides the Xcode flag to the parent process's version.  Previously it
ran Bazel query and caused the analysis phase to happen 2x on each
build.
The Bazel Xcode version reader program writes a full Xcode version based
on how Bazel will set this version for the `DEVELOPER_DIR`.
> [xcodeproj] Fix double analysis phase

- rules/xcodeproj.bzl
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/xcshareddata/xcschemes/TestImports-App.xcscheme
since projects usually have a large scale, the env vars an target can have might be a very large list that exceed xcode arg max limit (256 kb) This is resolved in MacOS 11 but for now we should not add the reference to the target so that xcode won't crash.
For use cases where we have to add it back, we can add a new flag for it or consider it when we refactor xcodeproj fule
> Remove pre/post action having references to build target (xcode crush if build target is at large scale)

- docs/framework_doc.md
- rules/features.bzl
- rules/framework.bzl
- rules/framework/vfs_overlay.bzl
- rules/library.bzl
- rules/providers.bzl
Add the ability to virtualize the framework structure. swift and clang
compile as frameworks but the files don't move and we load them via VFS.
The VFS is llvm's in-memory file system declared by JSON. VFS is already
in use but this uses it in a very different way.
This fixes many issues:
1. we don't hit O(n) deps includes - removing thousands of framework
search paths
2. we don't have to "clean" frameworks. This feature added quite a bit
of overhead and isn't necesary since it's declarative
3. imports are fully again. traditionally a build system uses -F on a
build directory. This causes problems with reproducible builds.
It cut clean build time in half in a big hybrid app from rules_ios
baseline. More interestingly, hot top level compiler invocations are
down nearly .5 orders of …
> Virtual hermetic frameworks

- rules/library.bzl
The line to determine umbrella headers will cause issues in some
scenarios. This PR reverts to the orginal, albeit more nuanced logic.
Additionally correct the comment which would lead us to believe that
this is OK to disregard.
Will work on getting this explified in rules_ios as a followup.
> Fix conflict with umbrella headers

- rules/framework.bzl
- rules/providers.bzl
Downstream targets can directly read them. A use case is to repackage a static framework into a dynamic framework.
> Exposes more fields in FrameworkInfo

- rules/library.bzl
This happens for static library where we have .a directly under xcframework. Not having a .framework under .xcframework.
The original logic assumes there is a .framework present and will not create targaet for vfs if not present. 
Fallback to name used for .xcframework, which is consistent with the other place that having the same logic. 
Tests is done against a downstream project target. The full test cases will be estabalished when we roll out VFS fully.
> Fix no vfs target generated if no .framework present in path

- rules/framework/vfs_overlay.bzl
- rules/xcodeproj.bzl
The previous code relied on assumptions about swiftmodules which may be
invalid, depending on the input.
Now:
- It puts the name of the parent in the framework if it's a
swiftmodule-directory. This handles user provided directory
swiftmodules. The code now checks if its a `.swiftmodule` because
previously, it could take _any_ swiftmodule and give it the name of the
parent: e.g. the build directory.
- It takes the name of the swiftmodule and puts it into the root as
opposed to computing it.
It can fall back to the code path with assumptions to improve useability
of the rule. There would need to be further refactoring remove this:
Ideally remove this "apple libary only" codepath in the future.
> Reduce VFS assumptions about swiftmodules

- rules/framework.bzl
- tests/ios/frameworks/strict-deps/BUILD.bazel
- tests/ios/frameworks/strict-deps/a/BUILD.bazel
- tests/ios/frameworks/strict-deps/a/lib.swift
- tests/ios/frameworks/strict-deps/b/BUILD.bazel
- tests/ios/frameworks/strict-deps/b/lib.swift
- tests/ios/frameworks/strict-deps/c/BUILD.bazel
- tests/ios/frameworks/strict-deps/c/lib.swift
If the swiftmodule isn't propagated upwards, it will cause issues when
re-compiling and re-linking in the case of a remote cache or when the
local cache is primed with existing state.
This an example serial chain of swiftdeps to showcase the situation
```
a->b->c
```
> [virtual-frameworks] fix transitive swiftmodule bug

- BUILD.bazel
- rules/framework.bzl
- rules/library.bzl
By default `rules_swift` propagates swiftmodules to includes when they
exist as a dep. For now, we need to propagate these as they were.
Additionally, it factors out SwiftInfo building to another function.
This is orthogonal to the change, but something we came up with in the
continued effort to make the framework large framework method a bit
easier to follow than originally.
> Fixes default swiftmodule include issue

- docs/framework_doc.md
- rules/framework.bzl
- tests/ios/frameworks/strict-deps/a/BUILD.bazel
When distributing a framework to third-party developers, we will want to include a Info.plist file into the framework.
This PR uses rules_apple's resource_actions.merge_root_infoplists to merge info.plists and converts them into binary.
> Supports Info.plist in framework

- rules/xcodeproj.bzl
This fixes 2 issue which manifest under certain clang files. We
ended up with the argument used for the swift frontend here.
Additionally, it was unintentionally excluding some hmaps from the
invocation.
> [virtual-frameworks] Fix issue with Sourcekit clang

- rules/framework/vfs_overlay.bzl
In order to correctly identify some imports as a framework import, clang
needs the entire subtree under an imported framework. The previous path
triggered an edge case in some vendor frameworks.
This builds out the VFS subtrees for a given set of paths in this situation,
and then adds them to the VFS.
This manifested in one very odd permutations of a vendor framework
when using umbrella headers the headers. I suspect it's more
generalizable than the previous logic overall.
> [virtual-frameworks] Fix non-modular framework umbrella error

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
- tools/xcodeproj_shims/WorkspaceSettings.xcsettings
In Xcode 13, the warning about the deprecation of the legacy build system was upgraded to an error. Enabling this setting makes it a warning again.
Found the setting name here: https://github.com/Kitware/CMake/commit/71a2664ebb0fd6a8d56eadee058aecc431a40594
> Suppress legacy build system error in Xcode 13

- rules/library.bzl
Without filtering, an error is raised for missing config_setting in rules_apple like so:
`no such target '@build_bazel_rules_apple//apple:ios_arm64e': target 'ios_arm64e' not declared in package 'apple' (did you mean 'ios_arm64'?)`
> Adding platform-arch filter for xcframework slices

- rules/xcodeproj.bzl
Fixes https://github.com/bazel-ios/rules_ios/issues/311
I tried to add a test for this at top level, but current test scripts rely on xcodeproj tests being under `tests/ios/xcodeproj`
> Fix project generation when xcodeproj rule is declared at the top level of the workspace

- rules/xcodeproj.bzl
- tests/ios/unit-test/test-imports-app/Header.h
- tests/ios/unit-test/test-imports-app/empty.swift
- tests/ios/unit-test/test-imports-app/main.m
When LLDB compiles swiftmodules during attachment and `po` it is missing
some clang importer arguments. This adds missing copts directly to
LLDB in the lldbinit.
Note that I have also added a _example_ test case for LLDB and clarified some of
the requirments here. For now, it atleast documents this requirment:
```
Xcode project: bazel run tests/ios/xcodeproj:Test-Imports-App-Project
&& open tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/
Scheme: `TestImports-App`
Breakpoints: tests/ios/unit-test/test-imports-app/empty.swift:6
Breakpoints: tests/ios/unit-test/test-imports-app/empty.swift:15
Xcode Version: 12.5.1
```
Longer term, can "Reverse sherlock" some LLDB automation testing from
swift-LLDB to verify debugging of many examples. Testing is further
blocked by getting the …
> Fix LLDB internal module compilation error

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/_swiftmodule.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/_swiftmodule.sh
- tools/xcodeproj_shims/installers/_swiftmodule.sh
Resolves #306 
Xcode 13 now stores swiftmodule index information the `Index` directory in derived data. This modifies the swiftmodule installer to copy to both locations.
(Credit @brentleyjones in **iOS-dev-at-scale**: https://ios-dev-at-scale.slack.com/archives/CJDFFEN4S/p1631798553000500)
> Copy swiftmodules to both Xcode 12/13+ locations

- WORKSPACE
- rules/framework/vfs_overlay.bzl
- rules/repositories.bzl
- tests/ios/frameworks/external-dependency/BUILD.bazel
- tests/ios/frameworks/external-dependency/BUILD.com_github_apple_swiftcollections
- tests/ios/frameworks/external-dependency/external_dependency.bzl
Fix external VFS paths
Currently, the VFS rule formulates a path relative to the BUILD file
path, to replicate the "exec path" in the java rules. Now this path
formulation include the repository name for external repos. Of course,
it isn't returned by `build_file_path`. We didn't have a test case and
thanks to @jschear, it's now up and running
Fixes #307
> Fix external VFS paths

- .github/workflows/tests.yml
- rules/framework/vfs_overlay.bzl
- rules/library.bzl
- tests/ios/unit-test/test-imports-app/BUILD.bazel
Conditionally adds VFS all targets, which right now has conditional side
effect to compile them all as virtual frameworks. In the interim we want
to include the VFS in order to pickup deps that are virtual frameworks.
It also includes a stopgap hack for issues with merging imported
frameworks. The inline comment may be addressed
Additionally, it builds the entire test suite with virtual frameworks
to pickup regressions.
> Conditionally compile with transitive VFS

- rules/app.bzl
So we can use: https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_application-ipa_post_processor
> Add ipa_post_processor to list of ios kwargs

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/installer
- tools/xcodeproj_shims/install.sh
This is mostly relevant if:
- Not using index-while-building
- Build a scheme with a non-app primary output
Specifically, headers were not being copied over because they were symlinks and the default behavior of rsync is to skip these. Xcode indexing would fail because the modulemap would point to these files that were not being copied to derived data.
> Use --copy-links in rsync call to copy symlink files

- rules/app.bzl
Add missing `include_symbols_in_bundle` to `_IOS_APPLICATION_KWARGS`
> Add include_symbols_in_bundle to _IOS_APPLICATION_KWARGS

- rules/framework.bzl
- rules/precompiled_apple_resource_bundle.bzl
- rules/repositories.bzl
The latest rules_apple includes an output_discriminator param to intermediates.file, so just adding that in.
> Add output discriminator param

- rules/library.bzl
Align the key in an xcframework's `slice` attribute
```
"platform": "macos",
```
to the `rules_apple` supported platforms. There, it's known as `darwin`,
many others call it `macos`
> Set apple platform type for macOS xcframework

- rules/library.bzl
👋 
This PR better supports strict imports, meaning [files only import what they use, and they import everything they use](https://forums.swift.org/t/supporting-strict-imports/42472). 
See documentation in code for the full context 🙏
> Allow opting out of the default umbrella header, to support strict imports

- rules/app.bzl
- rules/force_load_direct_deps.bzl
ld has different behavior when loading members of a static library VS objects
as far as visibility. Under `-dynamic`
- linked _swift object files_ can have public visibility
- symbols from _swift static libraries_ are omitted unless used, and not visible otherwise
By using `-force_load`, we can load static libraries in the attributes of an
application's direct depenencies. These args need go at the _front_ of the
linker invocation otherwise these arguments don't work with lds logic.
Why not put it into `rules_apple`? Ideally it could be, and perhaps consider a
PR to there .The underlying java rule, `AppleBinary.linkMultiArchBinary`
places `extraLinkopts` at the end of the linker invocation. At the time of
writing these args need to go into the current rule context where …
> A rule to link with `-force_load` for direct `deps`

- .github/workflows/tests.yml
- .github/workflows/xcode_select.sh
- WORKSPACE
- tools/toolchains/xcode_configure/BUILD
- tools/toolchains/xcode_configure/README.md
- tools/toolchains/xcode_configure/xcode_configure.bzl
- tools/toolchains/xcode_configure/xcode_locator.m
- tools/toolchains/xcode_configure/xcode_locator_stub.sh
- tools/toolchains/xcode_configure/xcode_version_flag.bzl
Fork Bazel's Xcode autoconfigure for usability improvements and debugging
Fork and improve Bazel's xcode configuration code. This is not a measure to fix
the problem, but to debug it and unblock CI. Github actions is incrediblly
flaky but Bazel should deal with a flaky host better and this is a weak point
(https://github.com/bazel-ios/rules_ios/issues/361)
Bazel puts this error in the build file which is a problem on the CI because it
swallows the error and it requires a user to clean --expunge. Bazel requires
the user to expunge because it thinks the repository was successfully written.
Probably a better pattern is to fail, but that won't shed light on the problem.
This is not just broken for CI but local developers. The plan is to use
rules_ios CI to reproduce this and gather more …
> Measures to debug Bazel's Xcode ingestion flake

- .gitignore
These are generated when run `tests/xcodeproj-tests.sh --clean`.
> Ignore Index directories in tests

- .bazelrc
- BUILD.bazel
> Avoid running xcode-locator which can be super slow (and can fail) if the machine has many Xcode versions

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/swiftmodules.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/swiftmodules.sh
- tools/xcodeproj_shims/installers/swiftmodules.sh
If you have the same module also compiled for the host tools, the macOS
one could overwrite the iOS one and cause indexing error, for example:
```
module 'SwiftProtobuf' was created for incompatible target
x86_64-apple-macosx12.0
```
> Only import iOS swiftmodules

- rules/library.bzl
One `apple_framework` target with `vendored_xcframeworks` in [cocoapods-bazel](https://github.com/bazel-ios/cocoapods-bazel) failed to build. Adding the `_MANUAL` tags for `native.alias` could solve this issue.
1. Checkout [cocoapods-bazel](https://github.com/bazel-ios/cocoapods-bazel)
2. run `bin/setup`
3. run `rake/spec`
The error log
```
ERROR: ./spec/integration/tmp/monorepo/transformed/Pods/OneTrust-CMP-XCFramework/BUILD.bazel:3:16: Configurable attribute "actual" doesn't match this configuration (would a default condition help?).
Conditions checked:
//Pods/OneTrust-CMP-XCFramework:OneTrust-CMP-XCFramework-import-OTPublishersHeadlessSDK.xcframework-ios_simulator_x86_64
//Pods/OneTrust-CMP-XCFramework:OneTrust-CMP-XCFramework-import-OTPublishersHeadlessSDK.xcframework-ios_arm64
ERROR: …
```
> Bug fix for "_xcframework"

- rules/import_middleman.bzl
- rules/library.bzl
Depending on what order build files were created by hand or generated this
logic had an ordering problem with the invariant. This hardens the logic and
scopes it to a platform level.
> Fix ordering assumptions in input xcframework dictionaries

- tools/toolchains/bazel4_local_config_cc/BUILD
Broaden the include validation predicate which was previously set to
/Applications. When using this toolchain, the validation will otherwise fail
```
/var/tmp/_bazel_x/53998339ce49dbe95d8d2305f25af2f8/external/build_bazel_rules_ios/rules/hmap/BUILD.bazel:11:11: Compiling rules/hmap/lines.c [for host] failed: undeclared inclusion(s) in rule '@build_bazel_rules_ios//rules/hmap:lines':
```
> [Apple Silicon] Fix error if Xcode.app is out of /Applications

- BUILD.bazel
When setting the simulator cpu explicitly to `ios_x86_64` the overridden value will not match. For instance when running under an Xcode project.
> [AppleSilicon] Fix non-default CPU for simulator

- rules/app.bzl
So consumers can customize this property
See: https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-ios.md#ios_application
> Add bundle_name to list of iOS application kwargs

- tools/m1_utils/update_static.sh
This PR fixes 2 output messages that are bothersome in Xcode when
building many targets. It doesn't intend to change any functionality.
1. Fix "error" when running through Sim ARM64 objs through patch script
2. Fix ar output when used in "fat object file" archives
Fixes #394
> [Apple Silicon] Small improvments to stderr of update_static.sh

- design/APPLE_FRAMEWORK.md
- docs/library_doc.md
- rules/library.bzl
- tests/ios/app/BUILD.bazel
- tests/ios/app/WithDefinesObjc/WithDefines.m
- tests/ios/app/WithDefinesSwift/withDefines.swift
Proposal to solve #400 by introducing `swift_defines` and `objc_defines`
**Why not stop supporting `defines`?**
Backwards compatibility in case consumers with more simple use cases are already setting this value
**Why not manipulate `defines` and extract swift/objc from it?**
The `defines` attribute is already in use for a while and it's being propagated "as is" so consumer could be setting `select()` statements in this attribute to handle different settings, meaning we can't assume this attribute contains a list that can be manipulated.
**Why add this as an explicit parameter in `apple_library`?**
It's a good way to ensure there's documentation for these attributes it's clear to consumers what is expected in each. Open to suggestions though.
> Add objc_defines and swift_defines

- rules/xcodeproj.bzl
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
Follow up for https://github.com/bazel-ios/rules_ios/pull/397, one last edge cases before resolving https://github.com/bazel-ios/rules_ios/issues/400 
Essentially the original fix was to allow consumers to pass defines independently to `objc_library` and `swift_library` and be able to wrap in single quotes only the objc ones. This way values like `FOO=A B C` can be set on the consumer side to be `\'FOO=A B C\'` and be properly propagated to the underlying `clang` invocation (Swift defines don't need that).
This PR is an edge case that I missed, we also have to wrap the LLDB `clang` defines in quotes to handle the case where a define with spaces is passed.
> Fix LLDB clang invocation defines

- tools/xctest_absolute_source_locations/BUILD.bazel
- tools/xctest_absolute_source_locations/xctest_absolute_source_locations.m
Based on https://github.com/ios-bazel-users/ios-bazel-users/blob/d99366f5bb0b8e945a1a758f832e1b65fb42044f/jump_to_test_failure.md
Enables jumping to test failures when using Bazel Xcode projects in
Xcode 12+, by expanding relative file URLs to be relative to the
SOURCE_ROOT environment variable, which is already set for all tests /
schemes.
This works OK for Xcode 12 and we'll need to patch this for Xcode 13.
This should be handled as part of rules_ios, instead of by the users of
it.
> Integrate XCTest stdout workaround for Xcode 12 - pass 1

- rules/repositories.bzl
This should have shallow_since and it pops in Xcode right now
> Add arm-to-sim attribute to silence warning

- rules/xcodeproj.bzl
Uses empty list when there is no direct targets. We assume that _TargetInfo.direct_targets is not None on line 946.
> Fixes xcodeproj error when there is no direct targets

- rules/import_middleman.bzl
- tools/m1_utils/update_dynamic.sh
- tools/m1_utils/update_static.sh
Xcode 13.1-13.2.1 workaround ( no issue for 12.5.1 ) Strip iOS
device outputs file to mitigate LLDB default SDK selection from
the DWARF entry - DW_AT_APPLE_sdk. No harm since many third party
dist binaries ship with release + DSYM. Without this, Swift
debugging is broken. To fix without stripping, implement a macho
rewriter that removes or updates DW_AT_APPLE_sdk. Upstream LLVM
has redesigned the logic and it's fixed there once devs have that
patch
> [apple.arm64_simulator_use_device_deps] 13.1-13.2.1 LLDB fix

- .gitignore
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/indexstores.sh
- tools/xcodeproj_shims/installers/_indexstore.sh
- tools/xcodeproj_shims/installers/indexstores.sh
Resolves https://github.com/bazel-ios/rules_ios/issues/421 
* Invoke `index-import` with `parallel-stride` using different values for Intel vs M1
* Kill `index-import` process early to make sure there's only one instance running at a time
* Ensure only valid stores with both `units` and `records` directories are propagated ([to prevent this failure mode](https://github.dev/MobileNativeFoundation/index-import/blob/7c67cc40fe691f5d78ffa1f6e71cf32d59cf56fc/index-import.cpp#L386-L391))
* Also adds more information to the logs to help us troubleshoot in the future (fixing one bug that was prevent logs to be echo-ed if no stores were found)
> Set index-import parallel-stride to n CPUs

- rules/import_middleman.bzl
Many device built deps will need this linked due to missing symbols, the
Xcode toolchain contains them in libswiftCompatibility51
We're not currently auto linking these dependencies and it's necessary
for a large portion of code. Enabled with apple.arm64_simulator_use_device_deps
> [apple.arm64_simulator_use_device_deps] Add libswiftCompatibility51

- rules/framework.bzl
```
Caused by: net.starlark.java.eval.Starlark: NullPointerException thrown during Starlark evaluation (**)
at <starlark>.link_multi_arch_binary(<builtin>:0)
at <starlark>._register_linking_action(/private/var/tmp/_b/a91c18bd9ce258d03b3a6b38c636ee8d/external/build_bazel_rules_apple/apple/internal/linking_support.bzl:167)
at <starlark>._bundle_dynamic_framework(/private/var/tmp/_b/a91c18bd9ce258d03b3a6b38c636ee8d/external/build_bazel_rules_ios/rules/framework.bzl:583)
at <starlark>._apple_framework_packaging_impl(/private/var/tmp/_b/a91c18bd9ce258d03b3a6b38c636ee8d/external/build_bazel_rules_ios/rules/framework.bzl:849)
Caused by: java.lang.NullPointerException: apple_framework_packaging attribute  is not defined
```
We hit a null pointer when feeding these frameworks to certian aspects. …
> Fix  NullPointerException under aspect actions

- rules/xcodeproj.bzl
- tests/ios/xcodeproj/BUILD.bazel
Change `configs` attribute to also requires the config type XcodeGen uses `debug/release`:
1. New `configs` API (from list to dict), **this is an API breaking change**:
```
Dictionary keyed at config name present in the .bazelrc file and values at one of these two config types: 'debug', 'release'
A Xcode build configuration will be created for each entry and a '--config=$CONFIGURATION' will
be appended to the underlying bazel invocation. Effectively allowing the configs in the .bazelrc file
to control how Xcode builds each build configuration.
If not present the 'Debug' and 'Release' Xcode build configurations will be created by default without
appending any additional bazel invocation flags.
```
2. `target_settings_by_config`:
```
Additional optinal dictionary with Xcode build settings …
```
> Add target_settings_by_config and pass config type in configs attribute

- rules/xcodeproj.bzl
This PR adds the ability to toggle the disable main thread checker boolean in the diagnostics tab of a scheme.  The previous behavior was using the xcode's default which is false, so the new xcodeproj() attribute default is also false.
xcodegen documentation for disableMainThreadChecker: https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpec.md#common-build-action-options
> Toggle disable main thread checker in for schemes

- rules/repositories.bzl
This fixes a problem with swift_binary in the current version
> [Xcode13.3] bump rules_swift

- rules/internal/framework_middleman.bzl
**Summary:**
Allow `bazelisk coverage …` to work with targets that come from `framework_middleman` since `_coverage_files_aspect_impl` accesses `[AppleBundleInfo].binary` when `AppleBundleInfo` exists. This plus https://github.com/bazelbuild/rules_apple/pull/1423 allow coverage to work when `framework_middleman` is involved.
> Populate `[AppleBundleInfo].binary` in `framework_middleman`

- rules/app.bzl
Add support for `version` in the `ios_application` macro:
https://github.com/bazelbuild/rules_apple/blob/b915183c461b6d404a7666312e7d7c1156e31ac6/apple/internal/rule_factory.bzl#L403-L409
This allows something like:
```Starlark
load("@build_bazel_rules_ios//rules:app.bzl", "ios_application")
load("@build_bazel_rules_apple//apple:versioning.bzl", "apple_bundle_version")
apple_bundle_version(
name = "Version",
build_version = "308963",
short_version_string = "2022.17.0",
visibility = ["//visibility:public"],
)
ios_application(
...
version = ":Version",
)
> Add support for `version` in `ios_application`

- rules/test_host_app/Info.plist
- tests/ios/unit-test/BUILD.bazel
- tests/ios/unit-test/TestSuiteObserver.swift
This fixes an issue in unit test bundles where defining `NSPrincipalClass` within a test bundle's Info.plist would cause a build failure due to merging plists.
This PR fixes this issue by removing the defined `NSPrincipalClass` key from the `Info.plists` used by the rules. This key is already automatically defined by Xcode for iOS and macOS app targets so I don't believe we need to define this key in the rules.
> Xcode sets the default value of this key to NSApplication for macOS apps, and to UIApplication for iOS and tvOS apps. For other types of bundles, you must set this key in The Info.plist File.
Source: https://developer.apple.com/documentation/bundleresources/information_property_list/nsprincipalclass
I've also added a unit test to assert this behavior, this new test fails in the …
> Fix: Remove NSPrincipalClass in rules Info.plist files

- rules/legacy_xcodeproj.bzl
- rules/repositories.bzl
- rules/third_party/xchammer_repositories.bzl
Cherry-pick all rules_ios changes to a fresh slate on 5.0.0 tag
Note:These tags are based on the bazel-version - see XCHammer docs for
convetion. It cherry-picks all changes to HEAD at a give bazel
release, then adds changes to this tag for the Bazel release in
question
> [XCHammer] rebase, cherry-pick tulsi to HEAD

- rules/repositories.bzl
- rules/third_party/xchammer_repositories.bzl
We don't need this as of: https://github.com/bazel-ios/xchammer/commit/4af612c9e9d9428f1c8dbeabe8eece9ebe30e6a9
> Remove xchammer_tulsi_aspects

- rules/legacy_xcodeproj.bzl
- tests/ios/frameworks/objc/BUILD.bazel
- tests/ios/xcodeproj/BUILD.bazel
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
Bug fix for `additional_files` in xcodeproj and add a test case
- the `additional files` are not included as input so when building with sandbox, bazel complains that the `additional_files` are missing with the following error
```
Spec validation error: Invalid file group "../../../../../../tests/ios/frameworks/objc/additional_files/foo.podspec"
``` 
- wrong xcodeproj JSON file is generated
Currently the generated JSON has the following contents for the additional files, which is not correct. The generated Xcode project will not include the additional files, i.e., the fileGroups correctly.
```
fileGroups:
- path: "/Users/tawang/Downloads/xcodegen-localized/rules-ios/objc/BUILD.bazel"
optional: true
```
According to the [doc](https://github.com/yonaskolb/XcodeGen/blob/master/Docs/ProjectSpe …
> bug fix for "additional_files" in xcodeproj

- rules/third_party/xchammer_repositories.bzl
If I run `bazel sync` with the latest rules-ios, it complains 
```
ERROR: An error occurred during the fetch of repository 'xchammer-Quick':
Traceback (most recent call last):
File "/private/var/tmp/_bazel_tawang/11e611afa2f11dfb00f2bd11ce6be2fe/external/bazel_tools/tools/build_defs/repo/git.bzl", line 174, column 30, in _new_git_repository_implementation
update = _clone_or_update(ctx)
File "/private/var/tmp/_bazel_tawang/11e611afa2f11dfb00f2bd11ce6be2fe/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
git_ = git_repo(ctx, directory)
File "/private/var/tmp/_bazel_tawang/11e611afa2f11dfb00f2bd11ce6be2fe/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
_update(ctx, git_repo)
File …
```
> Fix @xchammer-Quick commit SHA

- rules/repositories.bzl
- rules/third_party/xchammer_repositories.bzl
When using `git_repository` in WORKSPACE
```
git_repository(
name = "build_bazel_rules_ios",
remote = "https://github.com/bazel-ios/rules_ios.git",
branch = "master",
)
```
bazel build will emit warnings like below, which is treated is build errors in the generated xcode project. Adding `shallow_since` can fix this warning. 
```
DEBUG: Rule 'xchammer' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1652289435 -0700"
DEBUG: Repository xchammer instantiated at:
XXXX/WORKSPACE:235:23: in <toplevel>
/private/var/tmp/_bazel_tawang/11e611afa2f11dfb00f2bd11ce6be2fe/external/build_bazel_rules_ios/rules/repositories.bzl:118:23: in rules_ios_dependencies
Repository rule git_repository defined at: …
```
> fix git-repository warning

- rules/repositories.bzl
To pick up: https://github.com/bazel-ios/xchammer/pull/22
> Bump XCHammer to pick up missing _precompiled_apple_resource_bundle fix

- tools/xcodeproj_shims/output-processor.rb
Sometimes Bazel log will contain characters ruby cannot handle, so we need to encode it with ASCII and replace anything it does not understand, or downstream project may face `invalid byte sequence in US-ASCII (ArgumentError)` error when trying to do regex match.
Choosing ASCII because according to this article: https://www.cloudbees.com/blog/how-ruby-string-encoding-benefits-developers string is best to be in that encoding for best performance. The log we have can be assumed to be useful with ASCII value only and I don't see the need to encode in more expensive UTF-8, but we can certain use that encoding too.
> Encode incoming string with UTF-8 and replace any invalid ones with default

- rules/framework.bzl
The nature of this attribute led to it being cached indefinitely in the
analysis phase. In other words, previously, once Bazel would set it and
then it was cached until the analysis cache was invalidated either
directly or indirectly. Forward the value to `minimum_os_version`
directly, which is is part of the analysis cache key for C++ rules
> Fix `platforms` / os version analysis phase caching

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/indexstores.sh
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/indexstores.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/indexstores.sh
- tools/xcodeproj_shims/installers/indexstores.sh
Without `sort`, this `uniq` call is really doing nothing. If the same index store appears multiple times in the build event file (which is the case for [bazel-out/rules_ios_global_index_store.indexstore](https://github.com/bazel-ios/rules_ios/blob/bb1f602ea6fe1611b608fcd2e54165f1da554471/rules/library.bzl#L969)) we will pass it multiple times to `index-import` causing performance issues in complex apps.
> Correctly find uniq index stores

- rules/framework/vfs_overlay.bzl
This struct can potentially contain an int value in some scenarios.
This change ensures that this variable is
of the correct type before indexing into
its values
> Safer engagement with `curr_subdirs` struct

- .bazelrc
- rules/framework.bzl
- rules/precompiled_apple_resource_bundle.bzl
- rules/repositories.bzl
This PR attempts to update `rules_apple` and `rules_swift`. 
Primarily, taking the changes applied in the `rules_apple` repository as-is.
> Update rules_apple and rules_swift versions

- rules/repositories.bzl
```
DEBUG: Rule 'xchammer' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1653678531 -0700"
DEBUG: Rule 'arm64-to-sim' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1627075944 -0700"
```
> Fix `shallow_since` warns in `xchammer`/`arm64-to-sim`

- README.md
Hi, just noticed a broken link while reading README:
* Current: https://bazel.build/versions/master/docs/be/objective-c.html#objc_library
* Fixed: https://bazel.build/reference/be/objective-c#objc_library
> Fix broken link for objc_library rule

- rules/library.bzl
For vendored frameworks distributed as xcframeworks consumers might want to also propagate pre-generated `.dSYM` files. 
This is a valid attribute we were not populating in [apple_dynamic_framework_import](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-apple.md#apple_dynamic_framework_import).
> Pass dsym_imports to apple_dynamic_framework_import in xcframeworks

- rules/extension.bzl
- rules/internal/framework_middleman.bzl
- tests/ios/extensions/BUILD.bazel
Add new `ios_extension` macro to copy the functionality from `app.bzl`/`ios_application` that allows `AvoidDepsInfo` (among other things) to function.
> Add `ios_extension` macro to mimic `ios_application`

- rules/force_load_direct_deps.bzl
- rules/framework.bzl
To enable `link_dynamic` to be set via a `select`, shift the choice to force load or not into the implementation of the `force_load_direct_deps` rule. `should_force_load` should be set to `False` when there should be no additional `-force_load` linker args.
> Add ability to `link_dynamic` via `select`

- docs/framework_doc.md
- rules/app.bzl
- rules/framework.bzl
- rules/internal/framework_middleman.bzl
- rules/test/output/output_checker.sh
- rules/test/output/output_test.bzl
- tests/ios/app/BUILD.bazel
- tests/ios/extensions/BUILD.bazel
- tests/ios/frameworks/dynamic/BUILD.bazel
- tests/ios/frameworks/dynamic/a/BUILD.bazel
- tests/ios/frameworks/dynamic/b/BUILD.bazel
Continuation of https://github.com/bazel-ios/rules_ios/pull/507 the adds tests + populates the partials in the "correct" way:
- Add `executable_name` as a forward param to `ios_application` to change the underlying app binary name.
- Forward the `-fapplication-extension` linker flag within `_bundle_dynamic_framework` signaled by checking for `-fapplication-extension` in the underlying library's `linkopts`.
- Ensure the `_bundle_static_framework` has the proper `extension_safe_validation_partial` call as well despite it being linked differently where it's unlikely to be necessary.
- Update `output_test` to be able to confirm that files don't exist in `target`'s output as well.
- Add `//tests/ios/frameworks/dynamic:AppWithExtension_output_test` to confirm that the dependent dynamic …
> Add `-fapplication-extension` validation for `apple_framework`

- tools/m1_utils/update_static.sh
Building Apps with Bazel for Apple Silicon invokes conversion from arm64 binary to arm64 simulator binary. Unarchiving the binary file has a bug where when an archive file has distinct objects with names that are only different in casing, the extracted contents are incorrect (e.g. `lib_test.a` has `test.cpp.o` and and `TEST.cpp.o`, running using `ar` to extract objects, `ar -x`, content for the `TEST.cpp.o` is overwritten by that of `test.cpp.o` ). 
**Changes**
1. Handle the edge case described above
2. Simply the existing logic using `uniq`
> Fix bug in unarchive function for m1 

- rules/library.bzl
- tests/ios/frameworks/testonly/BUILD.bazel
Follow up to https://github.com/bazel-ios/rules_ios/pull/469 that propagates `testonly` to the `{module name}_data` target when the parent framework has resources.
> Fix analysis failure when providing `data` targets that are marked `testonly`

- tools/m1_utils/update_static.sh
**Background**
-D option is recently added to `uniq` tool, so change the code compatible to old Mac OS versions. 
**Explanation about the awk command used in this PR**
A few notes:
- awk will iterate objs.txt two times because objs.txt is input-ed twice.
- NR==FNR (FNR refers to the record/line number in the current file, NR refers to the total record/line number. ) is true only when iterating the objs.txt the first time, because FNR resets to 0 for each file, whereas NR keeps incrementing without resetting.
- each line of a file objs.txt is a name of an object (e.g. GL.cpp.o)
And here's the pseudocode of what this `awk command(awk 'NR==FNR {count[tolower($0)]++; next} count[tolower($0)]>1' objs.txt objs.txt > duplicate_objs.txt)` does:
```
count = {} # define empty dictionary count
if NR …
```
> [m1_utils] Fix -D not available to uniq

- rules/library.bzl
Improve xcframework compatibility with `--incompatible_disallow_empty_glob` by explicitly allowing empty results.
- `*.swiftmodule/*.*` doesn't match anything in a 100% Obj-C framework
- I applied the same change to `*.modulemap` for frameworks that would end up failing the `len(import_module_maps) > 0` check just below.
> Improve xcframework compatibility with `--incompatible_disallow_empty_glob`

- tools/xcodeproj_shims/xcodeproj-installer.sh
Gnu coreutils' cp (often installed with brew or nix) behaves slightly differently from mac's cp. Coreutils cp will not copy the contents of a symlink unless the src has a trailing slash, so we add one in this PR. Coreutils cp also will not follow symlinks with -r, unless -L is also passed, so we add -L.
I compared the resulting behavior of these invocations to confirm that 1) the coreutils cp behavior matches mac's behavior, and 2) mac cp behavior didn't change.
> Fix cp invocation bugs for gnu coreutils

- docs/2022_bazel_ios_con.md
Congratulations everyone 🎉! 2022 is turning out to be the year of Bazel-iOS.
We've done a ton of amazing work and are accelerating iOS development at scale.
I formally invite you to join us for a day of open community, fun, and low level
iOS build talks.
The event will be held September 29th in San Francisco, CA from 10:00AM -
5:00PST. We're solidifying the location and minor details. One benefit of the
event is getting everyone together IRL. We'll also have remote speakers and a
recording of talks where approved. To put it bluntly - we want to share the
amazing work we've done with the world!
This is an _open_ call for talks - _especially for contributors 😊_. Please send
@jerrymarino a quick description of your proposed talk by September 1st - e.g.
directly or email to …
> Request for talks for first annual open Bazel-iOS con

- tools/vmd/BUILD.bazel
We updated the build system to download `tart` releases which caused it
to be renamed to `download`.
Fix this by explicitly naming files in the tarball
> Fix issue with moving tart to a http_archive

- rules/library.bzl
There is a lot left to fix in these rules, and adding 'inc'
extensions is one. For now, permit them in sources and headers
> [Buildfarm] Allow  "inc" files in srcs/hdrs to be hermetic

- rules/import_middleman.bzl
- rules/internal/objc_provider_utils.bzl
We weren't passing headers upwards to deps from the import middleman.
Fix the provider to make them hermetic
> [Buildfarm][AppleSilicon] Make import_middleman hermetic

- rules/precompiled_apple_resource_bundle.bzl
- rules/repositories.bzl
Update `rules_apple` and then match the versions of the transitive rulesets:
- `rules_apple` to `1.0.1`: https://github.com/bazelbuild/rules_apple/releases/tag/1.0.1
- `rules_swift` to `1.0.0`: https://github.com/bazelbuild/rules_swift/releases/tag/1.0.0
- `bazel_skylib ` to `1.1.1`: https://github.com/bazelbuild/bazel-skylib/releases/tag/1.1.1
Mostly to allow those using newer versions of `rules_apple` that update `apple_support` since it removes an attribute used in `_precompiled_apple_resource_bundle`: https://github.com/bazelbuild/apple_support/commit/f7bcd10eebdfb427098fcaa73060fd6dd3f1aaea#diff-8da4c3cdbc3afa122c0237931cb6a8db95a2b10ce7d77ab56ab0c33bcfc5aa69L174
> Update `rules_apple` to `1.0.1`

- rules/library.bzl
These weren't fed to swiftc and are missing in buildfarm remote
execution
> [Buildfarm] Private headers hermetic for swiftc

- rules/library.bzl
- tests/ios/frameworks/objcpp/BUILD.bazel
- tests/ios/frameworks/objcpp/ObjCLib/C.h
- tests/ios/frameworks/objcpp/ObjCLib/C.m
- tests/ios/frameworks/objcpp/ObjCppMixedLib/A.h
- tests/ios/frameworks/objcpp/ObjCppMixedLib/A.mm
- tests/ios/frameworks/objcpp/ObjCppMixedLib/B.cpp
- tests/ios/frameworks/objcpp/ObjCppMixedLib/B.hpp
- tests/ios/frameworks/objcpp/ObjCppMixedLibTests/ObjCppMIxedLibTests.m
An alternative to https://github.com/bazel-ios/rules_ios/pull/304 that enables the existing C++ target.  Resolves https://github.com/bazel-ios/rules_ios/issues/537.
- Sends C++ sources into a separate target instead of the existing Obj-C target to enable different `copt` values for each.
- Re-uses the same mixed Obj-C and C++ test fixture, thanks @ivan-golub!
> Enables C++ support in srcs

- rules/legacy_xcodeproj.bzl
- tests/ios/xcodeproj/BUILD.bazel
- tests/xcodeproj-tests.sh
We override the `Text Settings` in our non-`legacy_xcodeproj` XcodeGen config:
```YML
options:
usesTabs: false
indentWidth: 2
tabWidth: 2
```
Add support for `options` to be overridden via the `project_options_overrides` in `legacy_xcodeproj`. It might seem weird that this requires an entire new `rule` impl but this is done since XcodeGen won’t process `”2”` correctly from a `string_dict` for arguments like `indentWidth` or `tabWidth`. `_ProjectOptionsInfo `, a new provider, allows the values to be forwarded to the JSON payload as the properly encoded `int` and `bool` values as expected by the underlying project gen tool:
```JSON
{
"options": {
"createIntermediateGroups": true,
"defaultConfig": "Debug",
"groupSortPosition": "none",
"settingPresets": "none",
"usesTabs": false, …
```
> Add support for project options in `legacy_xcodeproj`

- rules/framework.bzl
It's already supported in the apple_framework_packaging rule. We need to pass it from apple_framework to apple_framework_packaging.
> Supports exported_symbols_lists in apple_framework

- rules/third_party/xcbuildkit_version.bzl
The xcbuildkit_version.bzl file contains an assumption that the xcbuildkit repo was pulled via git_repository.  We pull it in via http_archive and as a result the rule has no commit field and bazel crashes during loading phase.
Error message:
```
File "/private/var/tmp/_bazel_egates/c4850d11fbeadd6bd3db71db3a1c0e4d/external/build_bazel_rules_ios/rules/third_party/xcbuildkit_version.bzl", line 26, column 12, in _get_ref
if rule["commit"]:
Error: key "commit" not found in dictionary
> Fixing git_repository assumption in xcbuildkit dep

- README.md
The README has been pretty out of date with with this repo actually does and is aiming to do
Addresses how people use it for Xcode generatiion and other abilities https://github.com/bazel-ios/rules_ios/discussions/564
> Add discussion bullet points to README

- rules/app.bzl
- rules/extension.bzl
- rules/framework.bzl
- rules/library.bzl
- rules/xcodeproj.bzl
- tests/ios/app/AppTestOnly/App.swift
- tests/ios/app/BUILD.bazel
- tests/ios/extensions/BUILD.bazel
- tests/ios/frameworks/testonly/BUILD.bazel
rules_swift was updated (https://github.com/bazelbuild/rules_swift/pull/868) to require passing `testonly = True` in order to link `XCTest` framework.
`rules_ios` currently doesn't forward the `testonly` arg to the internal rules we create for all cases, this means it's not currently possible to use an updated `rules_swift` with `rules_ios`. 
With this PR the latest `rules_swift` can be used with `rules_ios`.
> Forward testonly attribute for all rules

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/_indexstore.sh
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/_indexstore.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/_indexstore.sh
- tools/xcodeproj_shims/installers/_indexstore.sh
Sometimes when indexing, `index-import` eats all CPU and network resources, then the internet is cut out and the laptop is frozen. 
Setting `index-import` to the lowest priority can help with this problem. The CPU usage is still high but the laptop is responsive.
> set index-import priority to lowest

- rules/framework.bzl
- rules/import_middleman.bzl
- rules/internal/objc_provider_utils.bzl
- rules/library.bzl
- tests/ios/xcframeworks/StaticLib/BUILD.bazel
- tests/ios/xcframeworks/StaticLib/StaticLibFW/StaticLibFW.h
- tests/ios/xcframeworks/StaticLib/StaticLibFW/StaticLibFW.m
The `includes` attr of `objc_import` is supposed to propagate to targets that depend on it (see [docs](https://bazel.build/reference/be/objective-c#objc_import)) but the layers we have in `rules_ios` (`import_middleman` and `apple_framework_packaging`) were not doing that properly. 
This prevents depending on vendored static libs that might have `#include` statements that don't specify the module name, e.g., `#include <Foo.h>` instead of `#include <FooName/Foo.h>`. In many cases it's not an option to ask the vendor to change their code.
Regarding it's just incorrect to not propagate these includes and effectively break the `objc_import` intended behaviour. Additionally added one test case for this scenario. 
ps: Changes to `fetch_default_xcconfig` and `modulemap_generator` are meant to …
> static vendored lib missing include paths

- .github/workflows/tests.yml
- rules/repositories.bzl
- rules/test.bzl
- tests/ios/unit-test/BUILD.bazel
- tests/test-tests.sh
This new macro allows for you to specify a way to "split" an identical bundle into multiple rules with different args for each. To do this you'd specify the different arguments you want to in each split. The suffix of each split will be specified by the key in the dictionary, the different args will be the value. These args will be merged with the ios_test_kwargs specified.
For instance if we have:
`split_ios_test(name = "Foo", split_name_to_kwargs {"MyTestHost1": {"test_host" : //MyTestHost1}, "MyTestHost2": {"test_host": //MyTestHost2}})`
Then target //Foo would have 2 test rules created. 1 named `//Foo_MyTestHost1` and `//Foo_MyTestHost2` and will be packaged together in a test suite of `//Foo`.
**NOTE**
Another possible way to get this similar effect without putting it right in …
> Add ability to split a test bundle.

- .github/workflows/tests.yml
`macos-latest` has been / will be bumped to match `macos-12`, and our CI is still using Xcode 12.5.1.
Was running into this issue here: https://github.com/bazel-ios/rules_ios/actions/runs/3348628738/jobs/5547932746
Don't know if this is a temporary issue (rollout wasn't supposed to happen for a couple more weeks), but this should unblock CI. See https://github.com/actions/runner-images/issues/6384 for details on the change.
https://github.com/bazel-ios/rules_ios/pull/580 is my WIP on upgrading to the newer image. Could even go crazy and add the `macos-13` image once it's ready 😄
> Change macos-latest to macos-11

- rules/legacy_xcodeproj.bzl
- tools/xcodeproj_shims/xcodeproj-installer.sh
In order to capture some usage/timing metrics, I built a wrapper around `index-import`, but I need to make sure that the original binary gets copied into the generated project.
It might be worth making this even more generic so that _all_ the packed-in binaries include runtime dependencies instead of doing it piecemeal.
> Copy runfiles from index-import variants

- rules/library.bzl
Flips PCH feature to mitigate broken PCH ingestion in some cases as a default. There are issues w/o this even for rules_ios test cases on 13.3.1 and probably apps had to turn that on for this bump. Because there are no known down-sides and it was somewhat involved to debug and create the PCH feature - turn it on a sensible default.
> [Xcode 13.3.1] Flip on in Swift PCH fix

- rules/repositories.bzl
When building an `apple_framework` as dynamic, if that framework depends on an `apple_resource_group` or an `apple_resource_bundle` the build will fail because `validate_all_resources_owned` is set to true in rules_apple. This https://github.com/bazelbuild/rules_apple/pull/1747 adds a `default_owner` so the check will pass and the `apple_framework` will build properly. This PR updates updates the rules_apple dependency to the latest on the `bazel/5.x` branch that includes this fix.
> Updating rules_apple to point to the latest on the bazel/5.x branch

- .gitignore
- rules/library.bzl
- rules/repositories.bzl
- rules/third_party/xchammer_repositories.bzl
- rules/xcodeproj.bzl
- tests/ios/app/App/main.m
- tests/ios/app/FW/FW.h
- tests/ios/app/FW/FW.m
- tests/ios/xcodeproj/BUILD.bazel
Requires:
* https://github.com/jerrymarino/xcbuildkit/pull/49 
* https://github.com/bazel-ios/xchammer/pull/33 
TL;DR:
* Adds `xcbuildkit-data` to `.gitignore` since `xcbuildkit` will use this dir to cache indexing cache
* Load current path to global index store from symbol `GLOBAL_INDEX_STORE_PATH`
* Bump `xcbuildkit`, `xchammer` to pick up changes above and `Tulsi` to pick up lates fixes ([this](https://github.com/bazel-ios/tulsi/pull/7), [this](https://github.com/bazel-ios/tulsi/pull/8))
* `xcodeproj` now accepts `bazel_build_service_config` to configura the build service, for now overriding some paths to allow me to experiment with this for some time before making it fully configurable for customers. Also, adds a test case for this.
> Add ability to configure build service

- rules/library.bzl
The name is not unique enough and can conflict with other rules.
> Make the wrap_resources_in_filegroup rule name more unique

- rules/legacy_xcodeproj.bzl
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tools/xcodeproj_shims/xcodeproj-installer.sh
In Xcode 14, we see that the invocation of `builtin-infoPlistUtility` sometimes will come after the 'Build with bazel' script phase. When this happens, the plist value will get overwritten by the one we've specified in our rules. As we always provide a base Info.plist (as required by rules_apple) if none is specified, this stub seems unnecessary.
> [Xcode 14.x.x] Remove INFOPLIST_FILE setting from the legacy xcodeproj rule

- .bazelrc
Been noticing more actions timing out during waiting for the Bazel server to startup ([1](https://github.com/bazel-ios/rules_ios/actions/runs/3429530372/jobs/5715271970))
This increases the timeout to two minutes, this might be related to #580 due to macos-12 being slower / under heavier load for GitHub.
> Increase bazel server startup timeout

- rules/repositories.bzl
- rules/xcodeproj.bzl
Requires:
* https://github.com/jerrymarino/xcbuildkit/pull/51
* https://github.com/bazel-ios/xchammer/pull/34
Besides the bumps moves `bazel_build_service_config` to be a "top level" attr since it's not part of `project_config` anymore.
> Bump xchammer and xcbuildkit

- rules/repositories.bzl
- rules/xcodeproj.bzl
- tests/ios/xcodeproj/BUILD.bazel
Same as https://github.com/bazel-ios/rules_ios/pull/597 that was merged by mistake and it's now ready to be merged for real.
Requires:
* https://github.com/jerrymarino/xcbuildkit/pull/51
* https://github.com/bazel-ios/xchammer/pull/34
Besides the bumps moves `bazel_build_service_config` to be a "top level" attr since it's not part of `project_config` anymore.
> Bump xchammer and xcbuildkit (2)

- rules/library/xcconfig.bzl
- rules/library/xcconfig_test.bzl
- tests/ios/xcconfig/BUILD.bazel
This reverts commit f304c3721b23c426a37b33ceb8e739586c8219f1.
This mixes other kinds of semantics and would suggest to keep "import" semenatics of thses.
Ideally something like cocoapods "concat" is handled elsewhere: fixing the BUILD file generator / cocoapods-bazel to do `$(inherited)` or other merging. For instance if you need to concat or do inheritance of 2 settings - you'd have to concatenate out of this program:
```
xcconfig = { debug: [A] } <- optimization would be to remove this
xcconfig_by_build_setting = {
debug: [A] + [B]
release: [A] + [C]
}
```
> Revert "Fix issue merging xcconfig values that are lists (#590)"

- WORKSPACE
- docs/app_doc.md
- docs/apple_patched_doc.md
- docs/framework_builder_doc.md
- docs/framework_doc.md
- docs/hmap_doc.md
- docs/library_doc.md
- docs/plists_doc.md
- docs/precompiled_apple_resource_bundle_doc.md
- docs/substitute_build_settings_doc.md
- docs/test_doc.md
- docs/transition_support_doc.md
- rules/repositories.bzl
- tests/ios/frameworks/core-data-resource-bundle/BUILD.bazel
- tests/ios/frameworks/mixed-source/only-source/BUILD.bazel
- tests/ios/frameworks/sources-with-prebuilt-binaries/BUILD.bazel
- tests/ios/frameworks/target-xib-resource-bundle/BUILD.bazel
- tests/ios/frameworks/target-xib/BUILD.bazel
The first two are necessary to pull in some changes for explicit module compilation, but then proto changes required a bump to stardoc, and then I needed to regenerate the docs, and then libraries depending on XCTest now have to be testonly. 🪒 🐂
> Bump rules_apple, rules_swift, and stardoc

- rules/framework/vfs_overlay.bzl
- rules/hmap.bzl
Ran `aquery` to verify; the only change on `SwiftCompile` is to remove all the `-Xcc -fmodule-map-file=...` lines for the hmap and vfs files.
Fixes #538.
> Add SwiftInfo to hmap/vfs rules to suppress module map generation

- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/bazelinstallers/installer
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/install.sh
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/bazelinstallers/installer
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/install.sh
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/bazelinstallers/installer
- tools/xcodeproj_shims/install.sh
Xcode 14 no longer supports the legacy build system, so we're silently
being upgraded to using the new build system. One issue that surfaces
from this is that the `libXCTestBundleInject.dylib` starts being
injected into the test host app as a step in building the *app host*
instead of in building the *test bundle* (as it used to). This is
problematic, because we `rsync --delete` the app bundle as part of the
Bazel install script after the dylib is copied, and thus it gets purged.
One interesting finding is that even without this fix, it works fine in
Xcode 14 with iOS 15/16 simulators. This appears to be due to some
difference in dyld behavior between sims, where it is able to successfully
fall back and load this library from the SDK dir instead of embedded in
the host app, even though …
> Fix Xcode 14 missing `libXCTestBundleInject.dylib` when running tests

- .github/workflows/tests.yml
This should reduce load on CI when people like me keep pushing small changes to PRs and using up all the mac capacity.
Cribbed from:
https://docs.github.com/en/actions/using-jobs/using-concurrency
> Cancel old PR CI jobs when PR is updated

- rules/test.bzl
If a user were to pass `testonly` to a `ios_unit_test` target then it fails with duplicate kwargs error due to `testonly = True` being hardcoded in the rules.
This updates the rules to default to `true` for `testonly` file removing the `testonly` arg from kwargs to resolve the duplicate kwargs error.
Related change: https://github.com/bazel-ios/cocoapods-bazel/pull/82
> Fix duplicate testonly kwargs in test.bzl

- rules/BUILD.bazel
Adds a `bzl_library` for some of the documented `.bzl` files in the repository.
Why? This is required if dependent macros/rules in other repositories want to generate documentation using stardoc for their internal .bzl files that load `rules_ios`.
> Add bzl target for exporting .bzl files

- docs/plists_doc.md
- rules/app.bzl
- rules/extension.bzl
- rules/framework.bzl
- rules/plists.bzl
- rules/plists_test.bzl
- rules/substitute_build_settings.bzl
- rules/test.bzl
- tests/BUILD.bazel
- tests/ios/xcconfig/BUILD.bazel
- tests/ios/xcconfig/Info.plist
This PR adds support for substituting values in `xcconfig` into `infoplists` and `xcconfig_by_build_setting` in to `infoplists_by_build_setting`. 
In the current rules we have most of what is required to allow substitution of xcconfigs into the plist files but users must create their own macros to do this. Since this is a very common use-case for xcconfigs, and given that `rules_ios` directly supports `xcconfig` and `xcconfig_by_build_setting` it would be a better user experience to automatically performing this variable substitution for users of `rules_ios`
Given an `Info.plist`:
```xml
<plist version="1.0">
<dict>
<key>CFBundleIdentifier</key>
<string>${PRODUCT_BUNDLE_IDENTIFIER}</string>
...
<key>CustonXCConfig1</key>
<string>${CUSTOM_XCCONFIG_1}</string>
<key>CustonXCConfig2</key> …
```
> Add substitution support for Info.plist and XCConfigs

- rules/legacy_xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
It looks like in Xcode 14, it is now passing a `-dependency_info` arg to libtool. Without this change, Xcode 14 generates an error when trying to find the `*_libtool_dependency_info.dat ` output file for creating static library targets. I've confirmed that this change works for both Xcode 13 & Xcode 14.
> Have LIBTOOL use the ld stub as well

- .bazelrc
Handle https://github.com/bazelbuild/bazel/pull/14679 to prepare for Bazel 6.0.0.
> Remove `--experimental_worker_allow_json_protocol`

- rules/plists.bzl
- rules/substitute_build_settings.bzl
Today it formulates too long of files names for me on macOS. The total path size today is:
`(BuildFilePathLength + 2 * RuleNameLength + SuffixLength)`
Given Bazel supports a single rule with a given name per build file, we can safely eliminate this extra layer of namespacing. After the fix, the total path size is:
`(BuildFilePathLength + RuleNameLength + SuffixLength)`
Additionally:
- further reduce generated label / output sizes
- underscore generated rule names with _
- remove issue with ".." name suffix. This also gets us better looking plists names: For instance, a Foo dogfood plist gets you _Foo.dogfood.0.info.plist
> Cleanup plist output formulation

- rules/extension.bzl
We were forwarding the `xcconfig` and `xcconfig_by_build_setting` to the `rules_apple` rule which leads to an error.  Instead we should pop it from kwargs and use it as needed.
> Fix incorrectly forwarding `xcconfig` to extension

- rules/precompiled_apple_resource_bundle.bzl
This allows it to pass the `CcInfo` provider requirement for the `objc_library.deps` attribute:
https://github.com/bazelbuild/bazel/blob/7ccc66108f08f7b6c6f6e5229f70f29962ea19ce/src/main/starlark/builtins_bzl/common/objc/attrs.bzl#L88-L91
Release notes associated with the change/attribute:
>RELNOTES[INC]: objc_library now requires CcInfo in its deps.  If this breaks you, add empty CcInfo() to your rule.
> [Bazel6] Add `CcInfo` to `precompiled_apple_resource_bundle`

- rules/internal/framework_middleman.bzl
When using targets created with `rules_ios` within rules that expect `rules_apple` targets we may receive a failure since we are not forwarding the `product_type` of `AppleBundleInfo`. 
This PR sets the `product_type = apple_product_type.framework` 
Example failure:
```
aspect on framework_middleman rule //NonEmpty:NonEmpty-Unit-UnitTests.framework_middleman: 
return target[AppleBundleInfo].product_type in (
Error: 'AppleBundleInfo' value has no field or method 'product_type'
Available attributes: archive, archive_root, binary, bundle_id, bundle_name
```
> Forward apple_product_type for framework_middleman

- rules/apple_patched.bzl
Remove the “hack” that propagates the `ObjcProvider.module_map` into `ObjcProvider.header` field since it doesn’t exist anymore. This is sorta like https://github.com/bazelbuild/rules_apple/pull/1319 in `rules_apple` for handling this change in Bazel core/`ObjcProvider`:
https://github.com/bazelbuild/bazel/commit/8a2b711a2700740575904682066dbe1e5c9f6d02#diff-85a50fa66fc245291c6d06d99b941e9ecb570762fa6658cf10d7fc6b265a5742L129-L133
Error in Bazel 6.0.0:
```
$ bazelisk test --local_test_jobs=1 -- //... -//tests/ios/...
ERROR: /private/var/tmp/_bazel_matt.robinson/0e64031a9efbb95e4728094ee9457143/external/TensorFlowLiteC/BUILD.bazel:15:30: in _apple_framework_import_modulemap rule @TensorFlowLiteC//:TensorFlowLiteC:
Traceback (most recent call last):
File …
```
> [Bazel6] Remove `ObjcProvider.module_map` -> `ObjcProvider.header`

- rules/framework.bzl
Fix the following mismatch between the declared output and the `symlink`’d input:
```
$ bazelisk test --local_test_jobs=1 --apple_platform_type=ios --deleted_packages='' -- //tests/ios/...
…
ERROR: /Users/matt.robinson/Developer/rules_ios/rules_ios/tests/ios/frameworks/intentdefinition/BUILD.bazel:3:16: in apple_framework_packaging rule //tests/ios/frameworks/intentdefinition:ObjCIntentConsumer:
Traceback (most recent call last):
File "/Users/matt.robinson/Developer/rules_ios/rules_ios/rules/framework.bzl", line 854, column 43, in _apple_framework_packaging_impl
framework_files = _get_framework_files(ctx, deps)
File "/Users/matt.robinson/Developer/rules_ios/rules_ios/rules/framework.bzl", line 383, column 38, in _get_framework_files
header_out = _framework_packaging(ctx, "header", …
```
> [Bazel6] Avoid copying in `.h` directories into `Foo.framework/Headers`

- rules/repositories.bzl
Bumps `xcbuildkit` and `xchammer` to pick up:
* https://github.com/jerrymarino/xcbuildkit/pull/53
* https://github.com/bazel-ios/xchammer/pull/36
* https://github.com/bazel-ios/xchammer/pull/35
> Align objc flags between Bazel and Xcode

- rules/library.bzl
- rules/repositories.bzl
Requires: 
* https://github.com/bazel-ios/xchammer/pull/37
* https://github.com/jerrymarino/xcbuildkit/pull/54
Also, changes the global index store path for ObjC to match Swift's. Open to suggestions here if anyone sees this as a potential breaking change, alternative is to conditionally set this when using XCHammer and let the current value be the default.
> Align swiftc flags between Bazel and Xcode in XCHammer

- rules/library.bzl
- tests/ios/unit-test/BUILD.bazel
Fix issue where targets that define `features` would not get merged with the internal `swift_library`'s `features` causing an analysis failure:
```
File "/private/var/tmp/_bazel_jszumski/ed7e7efa198ffcfaf8285220a74bc6f4/external/build_bazel_rules_ios/rules/test.bzl", line 142, column 14, in ios_unit_test
_ios_test(name, rules_apple_ios_unit_test, rules_apple_ios_unit_test_suite, apple_library, **kwargs)
File "/private/var/tmp/_bazel_jszumski/ed7e7efa198ffcfaf8285220a74bc6f4/external/build_bazel_rules_ios/rules/test.bzl", line 62, column 28, in _ios_test
library = apple_library(name = name, namespace_is_module_name = False, platforms = {"ios": ios_test_kwargs.get("minimum_os_version")}, testonly = testonly, **kwargs)
File "/Users/jszumski/Development/cash-ios/Tools/Rules/library.bzl", line …
```
> Fix analysis failure for targets that define `features`

- rules/test.bzl
Without this different attributes like "visibility" are not able to be set on the test suites. This inherits the ios args that are passed into the test rule to also be passed into the test suite on split ios tests
> Pass the ios args to the test suite

- rules/framework.bzl
Ensure the `AppleBundleInfo.infoplist` value is a single `File` instead of a list like `rules_apple` wants:
https://github.com/bazelbuild/rules_apple/blob/4f2b1f840db65ba567f86e1e4b51d19612db2f57/apple/providers.bzl#L72-L74
This was introduced in https://github.com/bazel-ios/rules_ios/pull/607.
> Correct `AppleBundleInfo.infoplist` value

- rules/legacy_xcodeproj.bzl
- tests/ios/unit-test/BUILD.bazel
- tests/ios/xcodeproj/BUILD.bazel
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/xcshareddata/xcschemes/App.xcscheme
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/xcshareddata/xcschemes/ExampleExtension.xcscheme
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/xcshareddata/xcschemes/ExplicitHostedWithAppExtensions.xcscheme
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/xcshareddata/xcschemes/iOS-9.3-AppHost.xcscheme
Ensure that when extension schemes are created that they have corresponding targets as well.
Fixes https://github.com/bazel-ios/rules_ios/issues/637.
> [xcodeproj] Ensure extension targets are created when in schemes

- tools/toolchains/xcode_configure/xcode_locator.m
Update to latest, [`xcode_locator.m`](https://github.com/bazelbuild/bazel/blob/master/tools/osx/xcode_locator.m), to enable `--xcode_version=14C18` to work.
Example error:
```
$ bazelisk build --xcode_version=14C18 //tests/ios/unit-test/test-imports-app:TestImports-App
INFO: Invocation ID: 56c08719-2cb3-49d8-af7e-1a06d0be38f5
INFO: Build option --xcode_version has changed, discarding analysis cache.
ERROR: /private/var/tmp/_bazel_matt.robinson/0e64031a9efbb95e4728094ee9457143/external/local_config_xcode/BUILD:30:13: in xcode_config rule @local_config_xcode//:host_xcodes: --xcode_version=14C18 specified, but '14C18' is not an available Xcode version. available versions: [14.2.0.14C18, 14.0.1.14A400, 14.1.0.14B47b]. If you believe you have '14C18' installed, try running "bazel shutdown", …
```
> Add support for product version in `--xcode_version`

- tools/compile_only_aspect.bzl
In a big repo I'd like to compile the tree to vet refactoring. However, in the face of #542 we need more changes to fix disk growth. That aside, I generally don't want need to link, codesign, or bundle, so this gets an elemental subset of compiling only with a quick and dirty aspect.
It's useful for CLI development only and wouldn't be part of the core rules.
@congt  I think we can use this to some sort of "type checking" the build as well: just asserting it will compile for something like a merge queue
> [RFC] Basic aspect to  _just compile_ a subset

- rules/repositories.bzl
Uses the bazel-ios/rules_apple fork which has updates that need to be upstreamed before we can go back to using bazel's rules_apple
> Use bazel-ios/rules_apple

- rules/hmap/hmap.c
- rules/hmap/hmapbuild.c
Harden hmap logic. After updating to Bazel 6.0 I hav observed several invalid hmap files in `bazel-out` and `--disk_cache`s under load only. The system in question was running Bazel 6, intel, and macOS 12.5.2. This hardens the hmap code to fix 2 obscure/intermittent categories of failure.
1. Fix hmapbuild return code
First if a write fails in rules_ios - in  `hmapbuilder.c` isn't propagated. This is a longstanding bug and maybe masking other problems.
2. Call fsync to guard against data corruption
Per the man page
> fsync() causes all modified data and attributes of fildes to be moved to
> a permanent storage device. This normally results in all in-core
> modified copies of buffers for the associated file to be written to a
> disk.
> [hmap][Bazel 6.0] Harden hmap writes

- data/xcspec_evals.bzl
- tests/ios/xcconfig/BUILD.bazel
- tests/ios/xcconfig/WithEdgeCaseConfigs/WithEdgeCaseConfigs.m
Regression introduced in #644 due to change in `xcspec_evals.bzl`
The issue is the `DEFINES_MODULE` xcconfig expects a string `YES` or `NO`, the code now does a check for `"<YES/NO>" and "<YES/NO>"` which causes a Starlark crash. 
Instead, revert back to using `var == "YES"` to get the correct boolean type out of the xcconfig value. 
We should follow up to understand _why_ this was caused.
I added a test to ensure we catch something similar in the future with that particular value.
```
bazel build //tests/ios/app:AppWithConfigurableAttrs
Analyzing: target //tests/ios/app:AppWithConfigurableAttrs (59 packages loaded, 1262 targets configured)
FATAL: bazel crashed due to an internal error. Printing stack trace:
java.lang.RuntimeException: Unrecoverable error while evaluating node …
```
> Fix boolean operation Starlark xcconfig crash in Xcode 14.2 xcspec

- tools/compile_only_aspect.bzl
There may be many ObjCompile actions in a objc_library target.
> Fixes the compile_only_aspect

- .github/workflows/tests.yml
- README.md
- rules/framework.bzl
- rules/import_middleman.bzl
- rules/repositories.bzl
From time to time we'll evaluate supporting this to allow us to all run on HEAD and keep pushing / working together with minimal dammage.
Detect if the user is on Bazel 5+ and fallback to our tag of `rules_apple` and corresponding API. Because we depend on some of the more stable internals, this isn't such a big deal for now. Add CI vetting and a README note on the status.
Outside of this, a minor fix make it work for me: disable strict version validation we added around deps.
Bazel 6.0 has a number of open questions that will be answered later
> [LTS][Bazel 5] Provide minimum LTS support

- data/xcspec_evals.bzl
- data_generators/xcspec_extractor.py
This fixes the root cause underlying #654 (and overwrites the manual stopgap from #653). 
In Xcode 14, Apple changed their xcspecs to use implicit booleans as opposed to explicitly checking against YES/NO string values. For example, in the `Clang LLVM 1.0.xcspec`:
```
{
Name = "CLANG_ENABLE_MODULE_IMPLEMENTATION_OF";
Type = Boolean;
DefaultValue = YES;
CommandLineArgs = {
NO = ();
YES = ("-fmodule-name=$(PRODUCT_MODULE_NAME)");
};
Condition = "$(CLANG_ENABLE_MODULES) == YES && $(DEFINES_MODULE) == YES";
},
```
Became:
```
{
Name = "CLANG_ENABLE_MODULE_IMPLEMENTATION_OF";
Type = Boolean;
DefaultValue = YES;
CommandLineArgs = {
NO = ();
YES = ("-fmodule-name=$(PRODUCT_MODULE_NAME)");
};
Condition = "$(CLANG_ENABLE_MODULES) && $(DEFINES_MODULE)";
},
```
The changes in this PR should generate …
> Fix xcspec evals for Xcode 14.2

- rules/test.bzl
- tests/ios/app/BUILD.bazel
Thank to https://github.com/bazelbuild/bazel/issues/10799 we now have `exec_properties` and the tests are missing `exec_properties`, so set them. If you have different exec properties for inputs, you can set them with `exec_properties`
Conditional to not expand the size of the action graph
> [RBE] Plumb missing exec_properties field

- .github/workflows/tests.yml
- .gitignore
- tests/ios/xcodeproj/tests.sh
- tests/macos/xcodeproj/tests.sh
- tests/test-tests.sh
- tests/xcodeproj-tests.sh
This PR adds a way for people to run tests which test rules_ios xcodeproj rules tests.  Anytime anyone looks at a change that impacts transitions ( including myself ) it causing the world more confusion to figure out the magic encantation of the test program and rosetta. You can easily update the test fixtures with `--update` if you just care to fix the transitions.
I added assertions for rosetta if you work on arm64 - now it just fails to prevent people getting stuck on this.
Update the fixtures with:
```
arch -arch x86_64 /bin/bash -l -c ./tests/xcodeproj-tests.sh --update
```
Fixes #598
Tested and working end to end on the latest cut of macOS Montery and Xcode 14.1.
It needs a login shell or `xcodebuild` doesn't work.
> [M1][xcodeproj] CLI to update xcodeproj rules tests

- rules/repositories.bzl
When using the `ios_unit_test` rule, the `instrumentation_filter` flag was not being respected when running a `bazel coverage` command. https://github.com/bazelbuild/rules_apple/pull/1824 fixed this problem. This PR updates the version of rules_apple to point to the commit after https://github.com/bazelbuild/rules_apple/pull/1824 merged.
> Updating version of rules_apple so that instrumentation filter will work

- rules/test.bzl
Allow `test_coverage_manifest` to be used on the test rules.
https://github.com/bazelbuild/rules_apple/pull/1824
https://github.com/bazelbuild/rules_apple/blob/ca789914d90bb41ac68cd334d60dc365b66707d4/apple/internal/rule_factory.bzl#L219-L224
> Forward `test_coverage_manifest` to test rules

- rules/test_host_app/test_host_app.bzl
Adding 15.0 to the list of DEFAULT_MINIMUM_OS_VERSION_LIST in test_host_app.bzl. This will allow `ios_unit_test` targets with `minimum_os_version = 15.0` using `test_host = True` to work.
> Adding 15.0 as a version of the test host app to generate

- tests/ios/frameworks/sources-with-prebuilt-binaries/Gemfile
- tests/ios/frameworks/sources-with-prebuilt-binaries/Gemfile.lock
Was seeing this when pushing:
```
remote: 
remote: 
remote: GitHub found 2 vulnerabilities on bazel-ios/rules_ios's default branch (1 moderate, 1 low). To find out more, visit:        
remote:      https://github.com/bazel-ios/rules_ios/security/dependabot        
remote: 
```
Updating the gemfile to bump `activesupport` version and cocoapods to get rid of any possible issues here
See:  https://github.com/bazel-ios/rules_ios/security/dependabot for more info
> Update Gems from tests to fix possible security vulnerability

- rules/framework.bzl
- rules/repositories.bzl
https://github.com/bazelbuild/rules_apple/releases/tag/2.2.0
Handle https://github.com/bazelbuild/rules_apple/commit/6e41b943f9985c1fde71ad9a9ddb505937da0afb in `rules_ios`’s `framework_provider_partial` usage.
> Bump rules_apple to 2.2.0

- docs/BUILD.bazel
- docs/app_clip_doc.md
- docs/app_doc.md
- docs/extension_doc.md
- docs/framework_doc.md
- rules/app.bzl
- rules/app_clip.bzl
- rules/extension.bzl
- rules/framework.bzl
A follow-up to #670 where we talked about moving the rules_ios modified kwargs to explicit arguments in the macros. Additionally, generates missing docs & updates outdated documentation.
> Update macro arguments to specify rules_ios modified arguments

- .github/workflows/xcode_select.sh
New version of https://github.com/bazel-ios/rules_ios/pull/376 to use BuildBuddy remote cache for CI jobs. Only enabled for CI jobs at this point vs. in the `.bazelrc` to avoid being prescriptive for dev workflows.
> Add remote cache for CI jobs

- rules/framework/vfs_overlay.bzl
Running some tests using `--starlark_cpu_profile` in one big app we have and noticed some hot spots we can easily improve here. Nothing major but still a good optimization to make IMO.
The overall improvement at the `_framework_vfs_overlay_impl` level is from `109.82s` to down to `77.82s`:
before:
after:
I was surprised with how much time is spent on `append/extend/len` operations but I guess there's not much we can do here without revisiting the algo as a whole and see if there's a better way to go about generating the same outputs.
It's definitely weird that removing the macro `_get_external_contents` that was just concatenating strings has improved things and I ran the same "before vs after" profiles without making the change in this commit …
> Minor vfs perf improvements

- rules/transition_support.bzl
Similar to https://github.com/bazel-ios/rules_ios/pull/678, using `--starlark_cpu_profile` to find hot spots. Looking at `_apple_rule_transition_impl` now.
Before:
After:
> _min_os_version_or_none perf improvements

- README.md
- WORKSPACE
- rules/repositories.bzl
Prevents unnecessarily downloading XCHammer dependencies if there's no intent of using it. If they do want to use it they just need to invoke this new macro in their `WORKSPACE` file.
> Loading XCHammer is opt-in

- README.md
- WORKSPACE
- rules/xchammer_xcodeproj.bzl
- rules/xcodeproj.bzl
- tests/ios/xcodeproj/BUILD.bazel
Follow up to https://github.com/bazel-ios/rules_ios/pull/683
The previous PR wasn't handling this correctly, clients would still fail if they **don't pass** `load_xchammer_dependencies` to opt-out of loading XCHammer
```python
rules_ios_dependencies(load_xchammer_dependencies = True)
```
To truly make this opt-in clients need to load a different symbol. This is advertised as "alpha" software atm so breaking changes like this are expected.
> XCHammer is opt-in follow up

- CONTRIBUTING.md
- README.md
Adds a new `CONTRIBUTING` doc to the repository with focused content for maintainers. I've moved the Bazel 5.x discussion to there to not overwhelm new users.
I've also reformatted the README a bit and broke it down into a "Getting started" section. Let me know your thoughts.
This depends on #687
> Update README & add CONTRIBUTING.md

- rules/app.bzl
The `ios_applicatoin` in rules_apple has parameters `linkopts` and `additional_linker_inputs`.  This change makes the `ios_application` in rules_ios also supports them.
> Support `additional_linker_inputs` on `ios_application`

- .github/workflows/create_release.yml
Removes some directories from the final release archive that take a significant amount of space and aren't required for consumers.
```sh
du -h rules_ios.1.0.0.tar.gz
49M    rules_ios.1.0.0.tar.gz
```
```sh
du -h rules_ios.1.0.0.tar.gz
1.0M   rules_ios.1.0.0.tar.gz
```
> Prune release asset for rules_ios

- rules/framework.bzl
Propagate `CcInfo.compilation_context.framework_includes` in `apple_framework_packaging`. This is to address a problem described [here](https://github.com/qyang-nj/BazelPlayground/tree/main/Issue2).
> Propogate `framework_includes`

- rules/framework.bzl
This PR fixes https://github.com/bazel-ios/rules_ios/issues/569.
`apple_*_(xc)framework_import` provides `_SwiftInteropInfo` instead of `SwiftInfo`. In `apple_framework_packaging`, when [we merge the SwiftInfo](https://github.com/bazel-ios/rules_ios/blob/b1499fc08a7e4b7a7ba238fb4c9b089e6648ecbd/rules/framework.bzl#L901), the info from the framework import get lost there.
To fix the problem, we can add `swift_clang_module_aspect` to the `transitive_deps` attribute of `apple_framework_packaging`, which converts `_SwiftInteropInfo` to `SwiftInfo`. `swift_library` does this for `deps` as well.
> Fix transitive framework import in opt build

- rules/framework.bzl
This reverts commit 6f11291e4147185a87f5c65766b31897b9eb4ad7 (https://github.com/bazel-ios/rules_ios/pull/570). This fixes https://github.com/bazel-ios/rules_ios/issues/712 and is confirmed in https://github.com/bazel-ios/rules_ios/pull/713 (which can be merged after this is done since I don't have repo branch push access).
> Revert "use swift_clang_module_aspect on apple_framework_packaging.transitive_deps (#3) (#570)"

- rules/framework.bzl
- rules/import_middleman.bzl
- rules/internal/objc_provider_utils.bzl
**Retry merging PR #570, which solves issue #569.** The original PR got reverted because of issue #712.
`apple_*_(xc)framework_import` provides `_SwiftInteropInfo` instead of `SwiftInfo`. In `apple_framework_packaging`, when [we merge the SwiftInfo](https://github.com/bazel-ios/rules_ios/blob/b1499fc08a7e4b7a7ba238fb4c9b089e6648ecbd/rules/framework.bzl#L901), the info from the framework import get lost there.
To fix the problem, we can add `swift_clang_module_aspect` to the `transitive_deps` attribute of `apple_framework_packaging`, which converts `_SwiftInteropInfo` to `SwiftInfo`. `swift_library` does this for `deps` as well.
@mattrobmattrob @thiagohmcruz
> [Retry] Fix transitive framework import in opt build

- .bazelrc
- .github/workflows/tests.yml
- .github/workflows/xcode_select.sh
Before this change the CI and cache configs were being generated by `.github/workflows/xcode_select.sh` which makes it difficult for a contributor to find these and to then apply them.
Changes:
- New Bazel configurations that make it easier to reproduce CI setup and debug issues locally.
- New configs for testing specific tests that were previously only in the workflow file.
- Removes the `user.bazelrc` generation CI was doing in favor of the new `ci` and `cache` configs.
- Updates the workflows to use the new configs where needed.
Depends on #716
> Add remote cache and CI configs

- rules/library.bzl
Enabled since https://github.com/bazel-ios/rules_ios/pull/550.
> Remove out of date cpp library comment

- rules/library.bzl
apple_library has has supported include files with the suffix `.inc`. 
But this type of file is not allowed when creating a `PrivateHeadersInfo` provider
> support .inc file for func `_private_headers`

- rules/legacy_xcodeproj.bzl
Refactored `_xcodeproj_is_mixed` to `_target_is_mixed` to determine the boolean value of `mixed` on a per target basis.
This change solves the following indexing error seen when indexing swift-only or objc-only targets on Xcode 14.3.0:
`/<unknown>: underlying Objective-C module 'SomeSwiftOnly_App' not found`
Thanks to @thiagohmcruz for debugging this!
> Refactor _xcodeproj_is_mixed to _target_is_mixed

- rules/legacy_xcodeproj.bzl
Verifying if indexing continues to work on Xcode 14.3 and noticed that there's a better fix for an indexing issue I fixed recently.
* Undo `_target_is_mixed` check as the intent was to conditionally set `-import-underlying-module` to workaround an indexing issue
* After further investigation realized that the missing transitive `copts` this PR adds are enough to fix the same indexing issue I found at the time when `_target_is_mixed` was introduced as part of #661
> Propagate transitive ObjC and Swift copts

- rules/framework.bzl
- rules/repositories.bzl
Update `rules_apple` to https://github.com/bazelbuild/rules_apple/releases/tag/2.3.0 (https://github.com/bazelbuild/rules_apple/commit/915ac30a9fa1fd3809599a5ab90fa1c6640fe8dc) and handle https://github.com/bazelbuild/rules_apple/pull/1534.
> Update rules_apple to 2.3.0 + remove bitcode support

- rules/precompiled_apple_resource_bundle.bzl
Fix issue where a resource bundle's Info.plist value for `CFBundleName` incorrectly included the bundle extension.
In the generated plist:
```diff
-   "CFBundleName" => "ATMFinderResourcesbundle"
+   "CFBundleName" => "ATMFinderResources"
```
> Fix resource bundle's CFBundleName

- rules/app.bzl
Fix issue where `xcconfig` and `xcconfig_by_build_setting ` values for non-plist settings (e.g., Swift compiler flags) were not applied for `ios_application`.
I found this because we had `SWIFT_TREAT_WARNINGS_AS_ERRORS` set but didn't see `-warnings-as-errors` set on the swiftc invocation.
> Fix xcconfig passthrough for `ios_application`

- rules/framework.bzl
`rules_swift` has support for `symbol_graph` in `SwiftInfo`: https://github.com/bazelbuild/rules_swift/pull/838
The framework target should forward that as well
> Add support for forwarding symbol graph

- rules/framework.bzl
Getting an error when I pull a SHA of rules_swift  Error: create_swift_module() got unexpected keyword argument: symbol_graph
The call to create_swift_module gains affordances to deal with the older version of the API - predicated on the attrs struct
fixes #737
> Make symbol_graph argument conditional

- rules/framework.bzl
- rules/precompiled_apple_resource_bundle.bzl
- tests/ios/frameworks/dynamic/BUILD.bazel
- tests/ios/frameworks/dynamic/a/BUILD.bazel
- tests/ios/xcodeproj/Test-Mixed-Dynamic-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Mixed-Dynamic-App-Project.xcodeproj/xcshareddata/xcschemes/aWithResourceBundles.xcscheme
This is to handle a use case similar to the test case I'm adding in this PR:
```sh
apple_framework(
name = "aWithResourceBundles",
srcs = glob(["*.swift"]),
bundle_id = "com.example.aWithResourceBundles",
infoplists = ["Info.plist"],
link_dynamic = True,
platforms = {"ios": "10.0"},
resource_bundles = {
"aWithResourceBundles": ["data.txt"],
},
visibility = ["//visibility:public"],
xcconfig = {"APPLICATION_EXTENSION_API_ONLY": "YES"},
deps = ["//tests/ios/frameworks/dynamic/b"],
)
```
Specifically when these conditions hold 
1. When the key in `resource_bundles` matches exactly the `apple_framework` name
2. `link_dynamic` is `True`
3. An `ios_application` takes a dep in such framework
Then building the app
```sh
bazel build tests/ios/frameworks/dynamic:App
```
will fail with err
```sh …
```
> Differentiate `output_discriminator` when using `link_dynamic`

- BUILD.bazel
- rules/features.bzl
- rules/library.bzl
**Note**: note that this is an optional behaviour so backwards compatible.
* Introduce `swift.swift_disable_import_underlying_module` so consumers can opt-in to not always pass `-import-underlying-module` to `swift_library` targets [here](https://github.com/bazel-ios/rules_ios/blob/cf7d493d9cdcff9671fe074c4cfcdcbe540b4cd4/rules/library.bzl#L896-L898)
* Because `additional_swift_copts` above is now a `select` [_append_headermap_copts](https://github.com/bazel-ios/rules_ios/blob/cf7d493d9cdcff9671fe074c4cfcdcbe540b4cd4/rules/library.bzl#L896-L898) can't mutate `swift_copts` via `extend` so adopting the `+= ` pattern there, did the same for the other params just for consistency and so that `_append_headermap_copts` returns all updated `*_copts` values instead of only `swift_copts`
My …
> Add ability to disable passing the -import-underlying-module copt to swift_library targets

- rules/framework.bzl
It was previously hardcoded as as static library and led to confusion even though it was mainly unused at the time.
Fixes #742
> Remove invalid product type

- rules/precompiled_apple_resource_bundle.bzl
- tests/ios/frameworks/core-data-resource-bundle/CoreDataExample/Model.xcdatamodeld/.xccurrentversion
- tests/ios/frameworks/core-data-resource-bundle/CoreDataExample/Model.xcdatamodeld/Model 2.xcdatamodel/contents
- tests/ios/xcodeproj/BUILD.bazel
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
* In `_precompiled_apple_resource_bundle` explicitly pass `.xccurrentversion` files to `AppleResourceInfo` provider in the `datamodels` attribute
* Add a test case to exercise `.xccurrentversion` being picked up by `rules_ios`'s Xcode project generator (just because this wasn't being exercise before, the previous item is not a prerequisite for this to work in the `rules_ios`'s generator):
This is part of the work to make `rules_ios` work better with [rules_xcodeproj](https://github.com/MobileNativeFoundation/rules_xcodeproj) for those using it.
If one's `.xcdatamodeld` contains more than one version a `.xccurrentversion` file is used to set the current active one (represented by the ✅ in Xcode). When using `rules_xcodeproj` because `_precompiled_apple_resource_bundle` bundles just a …
> Pass xccurrentversions explicitly in AppleResourceInfo.unprocessed

- rules/precompiled_apple_resource_bundle.bzl
Follow up to https://github.com/bazel-ios/rules_ios/pull/747
While testing this in a more complex graph found that I've missed setting `owners` for the newly collected `.xccurrentversion` files.
@mattrobmattrob re our other thread on that, also learned that we can hit this code path with multiple `.xccurrentversion` files under the same target even though they're unique in their own `.xcdatamodeld` directories.
> Set xccurrentversion owners

- .bazelrc
- .github/workflows/preflight_env.sh
- .github/workflows/tests.yml
Configure bazelrc in the `preflight_env.sh` script
Ensure we enable existing remote cache on github actions
> Turn off remote cache for local dev, cleanup github actions UI clutter

- docs/test_doc.md
- rules/test.bzl
Add the ability to override stuff.
Test rules were impossible to extend and difficult reasoning about how it worked with rules_apple - which led to issues implementing new features like shard by class.
Test rules simply accept a `test_suite_factory`. On the default one, you can override some parts if necessary. _The default one could be much more generic - but at some point, I expect people to just make their own `test_suite_factory` VS adding too many abstractions to it_
Last: normalize all into a single bundle - otherwise it would duplicate tons of data and be un-useable at scale.
> [Test] Break massive ios_test function into factory

- tests/macos/xcodeproj/NonArcObject.h
- tools/xctest_absolute_source_locations/xctest_absolute_source_locations.m
Fixes warnings for a missing base case:
```
tests/macos/xcodeproj/NonArcObject.h:1:12: warning: class 'NonArcObject' defined without specifying a base class [-Wobjc-root-class]
@interface NonArcObject
^
tests/macos/xcodeproj/NonArcObject.h:1:24: note: add a super class to fix this problem
@interface NonArcObject
```
and a pointer mismatch:
```
tools/xctest_absolute_source_locations/xctest_absolute_source_locations.m:39:44: warning: incompatible pointer types passing 'NSString *' to parameter of type 'NSURL *' [-Wincompatible-pointer-types]
NSURL *workspaceURL = getWorkspacePath(testBundlePath);
^~~~~~~~~~~~~~
tools/xctest_absolute_source_locations/xctest_absolute_source_locations.m:14:39: note: passing argument to parameter 'testBundle' here
static NSURL *getWorkspacePath(NSURL …
```
> Fix warnings for a missing base class and pointer mismatch

- rules/internal/framework_middleman.bzl
- tests/ios/unit-test/test-imports-app/BUILD.GoogleMobileAds
Apple's > Xcode 4.x linkers have problems when SDK dylibs are first - Bazel 6.0 broke this due to refactoring. see changes in ( https://github.com/bazelbuild/bazel/blob/283ed362e6ccceb047553c2517a0331afd02db90/tools/osx/crosstool/cc_toolchain_config.bzl#L261 )
So this PR, is adding sdk_dylib to _end_ of the linker invocation to make this work as it did
> [Bazel 6.x.x] sdk_dylib at _end_ of the linker invocation

- rules/import_middleman.bzl
In Bazel 6.x.x the `static_framework_file` was migrated onto `imported_library` this PR completes the migration and is followup to the Bazel 6 work.
The related rules_apple change which updated `static_framework_file`: https://github.com/bazelbuild/rules_apple/commit/8d841342c238457896cd7596cc29b2d06c9a75f0
> [Bazel 6.x.x] sim_arm64 middleman fixes

- rules/test.bzl
- tests/ios/unit-test/BUILD.bazel
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/xcshareddata/xcschemes/DefaultHosted_bundle.xcscheme
Broken in https://github.com/bazel-ios/rules_ios/pull/754, this fixes by taking the given bundle_name or the name if not provided
> Fix not allowing custom bundle_name

- rules/library.bzl
The `import_middleman` code path ultimately leads to the [update_in_place](https://github.com/bazel-ios/rules_ios/blob/master/rules/import_middleman.bzl#L36-L41) script that adjusts deps for Apple Silicon. That feature is not necessary if the xcframework already contains a `arm64` + `sim` slice.
> Only update_in_place if arm64 sim slice is not present

- rules/framework/vfs_overlay.bzl
Comparing the top level `_apple_framework_packaging_impl` and `_framework_vfs_overlay_impl` nodes. Overall seems like `.append` and `.extend` are more expensive than `+=`? The delta goes up to the `root` node so I don't think this is just perceived improvement.
> Improves make_vfsoverlay performance

- .bazelrc
- .github/workflows/preflight_env.sh
- .github/workflows/tests.yml
- BUILD.bazel
- MODULE.bazel
- WORKSPACE
- WORKSPACE.bzlmod
- rules/module_extensions.bzl
- rules/repositories.bzl
Adds initial support for bzlmod to rules_ios.
Major changes:
- Update versions in `repositories.bzl` to use minimum supported bzlmod version
- Add `MODULE.bazel` and required files to enable bzlmod by default in Bazel 6+
- Enable bzlmod by default in the repository
Required workarounds:
- Disable bzlmod when running legacy .xcodeproj tests. This rule collects workspace name in an aspect which now resolves to simply `_main` in bzlmod. This doesnt seem to cause any actual issues with the generated project besides the repository being named `_main`. Proper fix is to have this use runfiles but I do not have enough context to make that change. 
Things to follow-up on:
- Add bzlmod support for stardoc
- This requires some more changes to bzl_library usage and update to Stardoc version, will do …
> Add support for bzlmod

- rules/repositories.bzl
- tools/vmd/vmd.sh
We saw these releases get deleted - use re-hosted cached sha
Further, fix issue with disk attachment in this release
> Update tart to 0.35.2 to cached version

- MODULE.bazel
- rules/repositories.bzl
The bzlmod PR marked `arm64-to-sim`, `rules_pkg`, and `tart` as development dependencies. There are some repos relying on the versions defined in these so include them in the WORKSAPCE file when using `rules_ios_dependencies`.
Fix #781
> Fix marking of development dependencies

- .github/workflows/tests.yml
- MODULE.bazel
- data/BUILD.bazel
- docs/BUILD.bazel
- rules/BUILD.bazel
- rules/framework/BUILD.bazel
- rules/internal/BUILD.bazel
- rules/library/BUILD.bazel
- rules/repositories.bzl
- rules/rules_apple_api/1_0/BUILD.bazel
- rules/rules_apple_api/2_0/BUILD.bazel
- rules/rules_apple_api/3_0/BUILD.bazel
Updates the dependencies of the latest versions, fixes some bzlmod warnings introduced by rules_apple 3 PR
```
WARNING: For repository 'build_bazel_apple_support', the root module requires module version apple_support@1.6.0, but got apple_support@1.11.0 in the resolved dependency graph.
WARNING: For repository 'build_bazel_rules_swift', the root module requires module version rules_swift@1.8.0, but got rules_swift@1.12.0 in the resolved dependency graph.
```
Additionally, moves the latest versions in `repositories.bzl` back to using the release archive instead of a GitHub on-demand archive. Not sure why those were changed
Finally, fixes issues with stardoc and rules_apple 3 + bzlmod.
It re-enables bzlmod for stardoc in CI
Fixes #783
> Update dependencies and use latest archives

- .bcr/metadata.template.json
- .bcr/presubmit.yml
- .bcr/source.template.json
- .github/workflows/generate_release_notes.sh
- README.md
Depends on #776.
This adds the required template files for https://github.com/bazel-contrib/publish-to-bcr an action which will publish to the Bazel central registry when new releases are tagged.
We'll need someone with repository admin access to approve the action configuration I requested.
> Add Bazel central registry files

- .bcr/presubmit.yml
- .github/workflows/create_release.yml
- BUILD.bazel
- MODULE.bazel
- tools/BUILD.bazel
Feedback from: https://github.com/bazelbuild/bazel-central-registry/pull/1052
> Update bzlmod files for first publish

- .github/workflows/preflight_env.sh
- .github/workflows/tests.yml
Attempt to speed up the slow `.xcodeproj Tests on Xcode 14.2.0` job on CI.
> Use remote cache when building in xcodeproj on CI

- MODULE.bazel
- data_generators/BUILD.bazel
- rules/framework/BUILD.bazel
- rules/test/lldb/BUILD.bazel
- rules/test/lldb/lldb_test.bzl
- tools/xcodeproj_shims/BUILD.bazel
For bzlmod you must declare dependency on things you `load`, in WORKSPACE mode `rules_python` is brought in transitively but in bzlmod we need to define this in `MODULE.bazel`.
Given that `rules_python` has beta support for bzlmod and that the Python rules we use are already part of the native rules, this PR removes all `load` of `rules_python` in favor of using the rules defined in the native module.
It also updates them to define the `PY3` source version.
> Remove dependency on rules_python

- .github/workflows/tests.yml
- WORKSPACE
- rules/repositories.bzl
Regressed in https://github.com/bazel-ios/rules_ios/pull/773
> Allow Bazel 6 users to explicitly opt-in to rules_apple 2.x

- rules/app.bzl
- rules/app_clip.bzl
- rules/extension.bzl
Fixes https://github.com/bazel-ios/rules_ios/issues/795. Bazel 7 seems to validate the usage of non-defined attributes better than Bazel 6 and lower.
~Testing Bazel 7 in CI using https://github.com/bazel-ios/rules_ios/pull/797.~ This gets us one step closer to being prepared for Bazel 7.
> Remove missing `output_discriminator` attribute usage

- MODULE.bazel
- rules/BUILD.bazel
- rules/internal/BUILD.bazel
- rules/internal/bazel_version.bzl
- rules/module_extensions.bzl
- rules/repositories.bzl
- rules/transition_support.bzl
- Create a new repo rule that contains the Bazel version for access in the analysis phase (`rules_ios_bazel_version`). This will just write the version from `getattr(native, "bazel_version", “”)` into a variable in `@rules_ios_bazel_version//:version.bzl`
- Use the Bazel version to conditionally handle the (now removed in Bazel 7) `--apple_compiler` & `--apple_grte_top` command line options.
- `apple_grte_top` removed in https://github.com/bazelbuild/bazel/commit/fb4106bdbd23c365337ea99704921ada7b86c2df
- `apple_compiler` removed in https://github.com/bazelbuild/bazel/commit/1acdfc422e724b4fe12c7bf5248086ab514ec4be
Work towards https://github.com/bazel-ios/rules_ios/issues/795.
> Conditionally handle `--apple_compiler` & `--apple_grte_top`

- .bazelrc
Allow users to add `--config=remote_cache` to `user.bazelrc` without all the other `ci` config flags from `ci_with_caches`.
> Decouple CI & remote cache config

- rules/precompiled_apple_resource_bundle.bzl
Fixes #800
Recent changes have made it so that `bundle_name` OR `executable_name` are used for the `CFExecutable` plist substitution: https://github.com/bazelbuild/rules_apple/commit/f909b0b6f31dee7ee9ba9998a92404eaeb7af727#diff-fd21ff183af5a0af8861d50117a7a377b04a0b7d9924600f424261b7db57e2deL279
This causes App store rejection, we should set `include_executable_name` to `False` to ensure its not substituted/included in the plist.
> Update precompiled_apple_resource_bundle to not include executable_name

- .github/workflows/tests.yml
This script seems to be failing [here](https://github.com/bazel-ios/rules_ios/actions/runs/6788374457/job/18454172023?pr=803), this works locally so trying to re-install the module before.
> Fix pkg_resources module not found in CI

- rules/apple_patched.bzl
- rules/framework.bzl
- rules/framework/vfs_overlay.bzl
Fix the following from https://github.com/bazel-ios/rules_ios/issues/795:
```
Error in fail: In order to use find_cpp_toolchain, you must include the '@bazel_tools//tools/cpp:toolchain_type' in the toolchains argument to your rule.
```
> Add `toolchains` to rules that use `@bazel_tools//tools/cpp:toolchain_type`

- rules/legacy_xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Mixed-Dynamic-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/fixtures/test_custom_output_path_expected_diff.txt
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
*What changed*
- Exposes the `BAZEL_DIAGNOSTICS_DIR` to the post build script by adding it to the `proj_settings_base`
> Add BAZEL_DIAGNOSTICS_DIR to proj_settings_base

- rules/import_middleman.bzl
This doesnt seem to have been updated to use the `apple_api_version` added in #773. As far as i can tell this was previously always returning `None`
> Fix usage of apple_api_version

- rules/app.bzl
- tests/ios/frameworks/dynamic/BUILD.bazel
- Before this change, using the "frameworks" parameter in ios_application resulted in an error: "Error in ios_application: rule(...) got multiple values for parameter 'frameworks'" because we are passing "application_kwargs" into the rules_apple rule which has the "frameworks" parameter copied over from "kwargs". Making this change actually pops the parameter from the correct dictionary which will remove the duplication error.
> Allow frameworks parameter to be used in ios_application

- rules/internal/framework_middleman.bzl
- rules/test.bzl
- tests/ios/unit-test/BUILD.bazel
Previously, using a `select` in the `test_host` parameter would result in the error:
```
ERROR: rules_ios/tests/ios/unit-test/BUILD.bazel:51:14: //tests/ios/unit-test:ExplicitHostedWithSelect.dep_middleman: expected value of type 'string' for element 0 of attribute 'test_deps' in 'dep_middleman' rule, but got select({"//tests/ios/unit-test:use_other_test_host": "//rules/test_host_app:iOS-9.3-AppHost", "//conditions:default": "//rules/test_host_app:iOS-14.0-AppHost"}) (select)
```
I simply removed the `test_deps` parameter as that wasn't really being used for anything of value that I could see. It was only ever being set to the `test_host` parameter or an empty list of which neither contain the `AvoidDepsInfo` information that was being deduplicated.
> Allow select in test_host parameter

- MODULE.bazel
This is more correct but also an attempt to fix the BCR issues in, for example, https://github.com/bazelbuild/bazel-central-registry/pull/1250.
> Update MODULE.bazel to exclude Bazel 7 and newer

- rules/library.bzl
If `apple.arm64_simulator_use_device_deps` is False, an xcframework providing slices for `ios-arm64` and `ios-arm64_x86_64-simulator` wouldn't select the second slice for an `ios_sim_arm64` build.  
```
ERROR: SomeFramework/BUILD.bazel:11:15: configurable attribute "actual" in //SomeFramework:SomeFramework-import-SomeFramework.xcframeworkdefault_vfs doesn't match this configuration. Would a default condition help?
Conditions checked:
//SomeFramework:SomeFramework-import-SomeFramework.xcframework-ios_arm64
//SomeFramework:SomeFramework-import-SomeFramework.xcframework-ios_simulator_x86_64
```
The configuration being built had these values:
```
FragmentOptions com.google.devtools.build.lib.analysis.config.CoreOptions {
cpu: ios_sim_arm64
host_cpu: darwin_arm64
...
}
FragmentOptions …
```
> Produce an alias for an xcframework's `ios_sim_arm64` slice if available

- rules/legacy_xcodeproj.bzl
So [OTHER_SWIFT_FLAGS](https://github.com/bazel-ios/rules_ios/blob/883cc859daffb1f02bd0e153fca39177d2fa7eb4/rules/legacy_xcodeproj.bzl#L836) gets `-import-underlying-module` if present. Without this indexing might fail in mixed modules.
I'm not sure why the aspect is not propagating the direct `copts` here and I'd rather not propagate everything and risk breaking the experience for folks. This legacy generator is going to be less and less maintained over time so not worth the effort of digging more here IMO (open to suggestions if anyone feels strongly about fixing all things `copts` in follow PRs).
> Ensure -import-underlying-module gets into the generated Xcode project

- rules/legacy_xcodeproj.bzl
- tests/ios/xcodeproj/Single-Static-Framework-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-BuildForDevice-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Imports-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-LLDB-Logs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-Mixed-Dynamic-App-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/custom_output_path/Test-LLDB-Logs-Project.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-AllTargets.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Single-Application-Project-DirectTargetsOnly.xcodeproj/project.pbxproj
- tests/macos/xcodeproj/Test-Target-With-Test-Host-Project.xcodeproj/project.pbxproj
- tools/xcodeproj_shims/build-wrapper.sh
**What changed**
- Added the `--starlark_cpu_profile` flag to generate the profile for builds in xcode
- Updated fixture files
> Generate starlark_cpu_profile for builds in xcode

- .bazelrc
- .github/workflows/tests.yml
- CONTRIBUTING.md
- MODULE.bazel
- README.md
This stops testing Bazel 5/rules_apple 2 in CI and bumps the support Bazel version in MODULE.bazel. It does not include any of the Bazel 5 related cleanup that is now possible. This is for an upcoming version 4.0.0.
Adds a table like the following to the read me:
| Bazel release | Minimum supported rules version | Final supported rules version
|:-------------------:|:-------------------------:|:-------------------------:
| 6.* | 2.0.0 | current
| 5.* | 1.0.0 | 3.2.2
| 4.* | 1.0.0 | 1.0.0
| rules_apple release | Minimum supported rules version | Final supported rules version
|:-------------------:|:-------------------------:|:-------------------------:
| 3.* | 3.* | current
| 2.* | 2.* | 3.2.2
| 1.* | 1.0.0 | 3.2.2
> Drop support for Bazel 5 & rules_apple 2

- .bcr/metadata.template.json
- .bcr/presubmit.yml
Now requires bazel version to be set, also switches to arm64 for the machines
> Fix BCR presubmit for new requirements

- .bazelrc
- .github/workflows/create_release.yml
- .github/workflows/preflight_env.sh
- .github/workflows/tests.yml
Updates GitHub CI to make it easier to add more Bazel/Xcode Versions.
Changes:
- Update `checkout` and `upload-artifacts` actions to `v4`, this fixes warnings we get on every PR for deprecated Node versions
- Add `matrix` strategy for all jobs, this adds a `bazel_version` and `xcode_version` which each job will be configured to run against. We can add Bazel 7 once #795 is done.
- Merge the `--config=vfs` and non-vfs job, this can be set with a custom matrix without duplicating the job code.
- Remove `--remote-cache` flag, this was set by every job already.
> Update CI for latest actions and to use matrix

- rules/test.bzl
- rules/utils.bzl
- tests/ios/app/BUILD.bazel
This makes changes to `test.bzl` to remove the default `internal_test_deps` being added to all snapshot tests. This is causing duplicate symbol issues in Bazel 7 as framework search path logic has changed. In Bazel 7, the snapshot test target can't depend on the runfiles lib without introducing duplicate symbols at link time, this is because the `BazelRunfiles` target it depends on already links the runefiles lib. This updates the rule / usage of it to pass this dependency explicitly so it can be removed in the bazel 7 branch but maintained here for others who need it.
Changes:
- Dont set `interal_test_deps` to have a default value for snapshot tests
- Explicitly set each key word argument in each test factory, this stops issues like this from coming up again in the future
> Fix duplicate symbols for test rules

- rules/force_load_direct_deps.bzl
- rules/internal/framework_middleman.bzl
- rules/transition_support.bzl
I'm trying to reduce custom stuff in `transition_support.bzl` so we can copy it again from `rules_apple` directly because its changed a lot for Bazel 7. 
This removes the constant to add transition support, ive seen this just copy-pasted into the rules in other repos, it simplifies it and removes the need to use `dicts`
> Remove split_transition_rule_attrs to simplify transition_support

- rules/framework.bzl
- rules/framework/BUILD.bazel
- rules/framework/vfs_overlay.bzl
- rules/precompiled_apple_resource_bundle.bzl
Prepares our mac and xplat toolchains for Bazel 7
Changes:
- Replace usage of `"@bazel_tools//tools/cpp:current_cc_toolchain"` with `"@build_bazel_rules_apple//apple:default_cc_toolchain_forwarder"`
- Rename `_toolchain` to `_mac_toolchain`, this matches rules_apple and better represents that the toolchain is for the host platform
- Add `cfg = "exec"` to the mac and xplat toolchains
- This is required to fix toolchain resolution errors on Bazel 7. These toolchains are for the host and so `exec` is correct here. This is the same cfg they use in rules_apple
> Update toolchains support for latest rules_apple and transitions

- rules/library.bzl
Adds support for `package_name` arg of `swift_library`. I also updated the kwarg forwarding to match the way we do it in `framework.bzl` and the other macros.
> Forward package_name to swift_library part of apple_library

- rules/framework.bzl
There's an internal use case for us that involves passing others types of deps to `apple_framework_packaging` that might not have the `apple_common.Objc` provider (`cc_library` targets). This check makes this assignment "safer" but also enables others also passing custom deps here.
> Safer objc_provider assignment in apple_framework_packaging

- rules/framework.bzl
- rules/library.bzl
Saves analysis time since it implies less rules impls to go through and less configured targets to process
> Do not declare force_load and VFS targets unnecessarily

- rules/precompiled_apple_resource_bundle.bzl
**Why this is needed?**
`fake_rule_label` was as a workaround and I'd like to remove it and use swift_module.
This pr is a continuation of https://github.com/bazelbuild/rules_apple/pull/2335.
If we try to build 2 different targets with same module name - plist generation will fail due to rule name collision as `fake_rule_label` is used, which was created from `swift_module` or `bundle_name`
**What has changed?**
Using `swift_module` for compiling assets, plists, storyboards, etc. instead of `fake_rule_label`. Now, each plist generation action has it's own rule name which has no name collision
**NOTE**
This PR Requires `rules_apple` to be at least 3.2.0, so I'll fix tests once it's updated
> Removed fake_rule_label from precompiled_apple_resource_bundle_impl and using swift_module instead

- MODULE.bazel
- README.md
- rules/repositories.bzl
3.5.1 [includes a fix](https://github.com/bazelbuild/rules_apple/pull/2444) we need to get in for `codesigntool` to work correctly. This increases min version of rules_apple to 3.5.1 for version 4.3.1 of rules_ios (to be released)
> Update to rules_apple 3.5.1 minimum supported version

- rules/force_load_direct_deps.bzl
- rules/framework.bzl
- rules/import_middleman.bzl
- rules/internal/framework_middleman.bzl
- rules/internal/objc_provider_utils.bzl
- tests/ios/xcodeproj/Test-MultipleConfigs-Project-WithTransitiveFlag.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-MultipleConfigs-Project.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/Test-With-Host-App-With-AdditionalPrebuildScript.xcodeproj/project.pbxproj
- tests/ios/xcodeproj/TestWithHostApp.xcodeproj/project.pbxproj
In Bazel 7+ `ObjcProvider` no longer supports/provides the required linking attributes.
The migrations is detailed here: https://github.com/bazelbuild/bazel/issues/16939. In summary, as part of the migration, the `ObjcProvider` fields which previously provided linking related information are now now longer providing that info. In addition to this, a new flag: `--incompatible_objc_linking_info_migration` was added to further delete these link attrs from the `ObjcProvider` making it an error if the attr is used or set.
The goal of this PR is to address support for `ObjcProvider` migration and to instead use the correct linking information from `CcInfo`. This will support both Bazel 6/7+. It does not try to support `--incompatible_objc_linking_info_migration` as that requires more changes …
> Update rules for ObjcProvider deprecations

- .bcr/presubmit.yml
Similar to https://github.com/bazelbuild/rules_apple/pull/2377, see: https://github.com/bazelbuild/bazel-central-registry/pull/1842
> Disable builtin CC toolchain for BCR tests

- rules/framework/vfs_overlay.bzl
This `data` struct is already included in `vfs_info.values()` here: https://github.com/bazel-ios/rules_ios/blob/311ba90785a7be2445f12e677beb7d32aead22e6/rules/framework/vfs_overlay.bzl#L387
> Stop processing data twice in make_vfsoverlay

- rules/plists.bzl
- rules/precompiled_apple_resource_bundle.bzl
- rules/test/lldb/lldb_test.bzl
`to_json` was removed from `struct` in latest Bazel versions. This is backwards compatible from Bazel 6+
> Update usage of `to_json` to `json.encode`

- rules/library.bzl
- tests/ios/frameworks/dynamic/b/BUILD.bazel
- tests/ios/xcodeproj/Test-Mixed-Dynamic-App-Project.xcodeproj/project.pbxproj
Similar to how rules_apple supports this, add an `extension_safe` attr handling which automatically sets `-fapplication-extension`.
> Add support for `extension_safe` attr

- rules/import_middleman.bzl
Continuation of: https://github.com/bazel-ios/rules_ios/pull/873
While testing Bazel 7 hit some build failures due to missing `-F` flags in the invocation.
I could set other attributes here too but since I'm not super familiar with this rule I'd rather add what is missing progressively as I run tests in Bazel 7.
> Bazel 7: Set framework_includes in import_middleman

- rules/library.bzl
- tests/ios/frameworks/dynamic/b/lib.swift
When using `extension_safe` the `copt` for the objc/swift library must also supply `-fapplication-extension`/`-application-extension`
> Fix extension_safe attr not passing copts

- rules/library.bzl
This fixes a missing `_swift_vfs.yaml` error related to the changes in: https://github.com/bazelbuild/rules_swift/pull/1191
Fixes #875
> Update for rules_swift 2.x

- rules/library.bzl
This moves resource generation (and being added to `deps`) below the `framework_vfs` creation which uses the `deps`
With the change in #879 to add the vfs to the `swiftc_inputs`  instead of the `deps` of the `swift_library` the `framework_vfs` was now also forwarding the resources (because it gets added to `deps` after generation) to other rules (like `rules_xcodeproj`) which collect extra files from this the `swiftc_inputs` attr. This led to duplicated resources in the project as they're collected from `resources` and now the transitive `deps` of the `framework_vfs`
AFAIK resources aren't needed for the `framework_vfs` rules and so this change should resolve the new `rules_xcodeproj` incompatibility while making the `deps` to the `framework_vfs` more scoped.
> Move resource generation below framework vfs

- rules/library.bzl
In #879 we added the extended modulemap to the `swiftc_inputs` below this line. This PR removes the non extended modulemap from being added as an input as we only need the extended version.
> Remove redundant modulemap in `swiftc_inputs`

- MODULE.bazel
This is required to support both rules_swift 1.x and 2.x
> Increase max compatibility level for rules_swift to 2

- .github/workflows/preflight_env.sh
This should let us ensure our rules have no issues with BwtB in Bazel 7+. The Bazel 6 job remains the same.
> CI: Bazel 7 tests use Build without the Bytes

- rules/framework.bzl
- rules/framework/vfs_overlay.bzl
Adds the public headers to the `CcInfo` compilation contexts
> Add `direct_public_headers` to CcInfo `compilation_context`

- rules/framework/vfs_overlay.bzl
- rules/hmap.bzl
Predelcared outputs are deprecated and discouraged, instead use `declare_file` to explicitly declare these outputs. See: https://bazel.build/extending/rules#deprecated_predeclared_outputs
> Remove usage of predeclared outputs from rules

- rules/framework.bzl
> Remove `_headermap_builder` from `framework.bzl`

- rules/library.bzl
When the `swift.swift_disable_import_underlying_module` is provided via the `features` attr this would previously do nothing, now it properly stops using `-import-underlying`
> Handle `swift.swift_disable_import_underlying_module` in `features`

- rules/hmap.bzl
Reverts bazel-ios/rules_ios#888
> Revert "Add headers to `headermap` action `inputs`"

- rules/library.bzl
To repro, run `bazel clean; bazel build //tests/ios/frameworks/mixed-source/only-source:SwiftLibrary -s --sandbox_debug --strategy=SwiftCompile=sandboxed` and got 
`<unknown>:0: error: underlying Objective-C module 'SwiftLibrary' not found` error
using`bazel aquery //tests/ios/frameworks/mixed-source/only-source:SwiftLibrary_swift` to look at input list, realized `bazel-out/darwin_arm64-dbg/bin/tests/ios/frameworks/mixed-source/only-source/SwiftLibrary-modulemap/SwiftLibrary.modulemap`  entry is not there even though that's sth generated by the module_map generator
So adding this fixed the issue because sandbox can now pick up this file 
Next step: setup CI job here that run everything in sandbox mode, try to fix anything that is broken in another PR
> Fix apple_library rule not working in sandbox when do `SwiftCompile` in mixed sources

- .bazelrc
- .github/workflows/tests.yml
- rules/library.bzl
- tests/ios/unit-test/test-imports-app/TestImports-Unit-Tests-Bridging-Header.h
- tests/ios/unit-test/test-imports-app/test.swift
What changed:
1. Add sandbox on/off to testing matrix, so we have 2 bazel version * VFS on/off * sandbox on off = 8 tests in total ATM
2. Fix redefinition of `AppErrorCode` enum error in sandbox mode by removing the extra import in bridging header. The tests still works and can catch renaming of the enum for example. Why it was working in non sandbox mode is unknown
3. Add `sandbox` config to include all settings needed to pass CI. specifically allow a small set of actions to run locally.
Why this change:
To add CI coverage to sandbox mode to ensure no regression on it, now that we have fixed issues with sandbox mode in https://github.com/bazel-ios/rules_ios/pull/894
Discussion:
CI duration might be a concern, we can exclude certain combo in the test matrix if we want, it's possible with …
> Add sandbox mode to CI testing matrix

- rules/library.bzl
1. When generate_default_umbrella_header is set to False, still add statements around `extern double {module_name}VersionNumber;` to umbrella header so that clang can resolve the situation when module_name is the same for two different modules (where their path is diff).
2. When generate_default_umbrella_header is set to False, use `extern` instead of `FOUNDATION_EXPORT` since `FOUNDATION_EXPORT` is `extern` and trying to define it in `else` clause will cause `warning: ambiguous expansion of macro 'FOUNDATION_EXPORT'` error.
[The original PR](https://github.com/bazel-ios/rules_ios/pull/348) that introduced the flag `generate_default_umbrella_header` essentially wants to not import UIKit/Foundation to restrict on what to import by default, which is a good thing. However, it kinda overkill …
> Avoid umbrella header crash error in remote compilation when no default umbrella header generated

- .bazelrc
- MODULE.bazel
- rules/explicit_module/sdk_clang_module.bzl
- rules/module_extensions.bzl
- rules/xcode_sdk_frameworks.bzl
It scans and configures all SDK frameworks which are required for explicit module builds.
Specifically, it 1) uses the bazel_tools//tools/osx:xcode_configure.bzl to fetch all local Xcode infos,
2) finds all frameworks under the xcode SDK path,
and 3) uses the swiftc -scan-dependencies mode to fetch the dependency graph among all Swift and Clang SDK modules.
We use swift_module_alias to represent a Swift SDK module and sdk_clang_module for a Clang SDK module.
This PR is based on the previous attempt to support SDK frameworks: https://github.com/bazel-ios/rules_ios/pull/562
Runs `bazel build --config=explicit_modules --nobuild @xcode_sdk_frameworks//...` and inspects the generated repository at `$(bazel info output_base)/external/_main~xcode_sdk_frameworks~xcode_sdk_frameworks`.
The …
> Adds the repository rule xcode_sdk_frameworks

- rules/library.bzl
The normal modulemap was added in https://github.com/bazel-ios/rules_ios/pull/894 and the extended modulemap is only for the objective-c part of the library so we shouldn't add it for the swiftc_inputs
> Remove extended modulemap from swiftc_inputs

- .github/workflows/tests.yml
This adds another matrix for testing the latest rules_apple and rules_swift without having to update our `MODULE.bazel`/`WORKSPACE.bazel` files.
NOTE: the latest rules dont work fully yet so im expecting these jobs to fail. I'll leave the latest jobs as **not required** and mark the rest **required** until we fix support for the latest rules.
> Add CI tests for latest rules_swift and rules_apple

- .bazelrc
- example/explicit_module/BUILD.bazel
- example/explicit_module/main.swift
- example/explicit_module/modules/BUILD.bazel
- example/explicit_module/modules/CarModule.swift
- example/explicit_module/modules/main.swift
- rules/explicit_module/sdk_clang_module.bzl
- rules/explicit_module/sdk_swiftmodule_import.bzl
- rules/xcode_sdk_frameworks.bzl
* Reimplemented sdk_clang_module to support interdependency among sdk_clang_modules
* Adds rule sdk_swiftmodule_import to support SDK swift modules
* Updates xcode_sdk_frameworks to allow a swift_binary to build with explicit SDK modules. Also updates the explicit_modules example to build with SDK modules.
`bazel run --config=explicit_modules example/explicit_module:hello_world`
> End-to-end support of SDK clang and swift modules

- rules/hmap.bzl
One of the CI error is:
```
error: generate-pch command failed with exit code 1 (use -v to see invocation)
tests/ios/unit-test/test-imports-app/TestImports-App-Bridging-Header.h:1:9: error: 'TestImports-App/Header2.h' file not found
#import <TestImports-App/Header2.h>
^
1 error generated.
<unknown>:0: error: failed to emit precompiled header 'bazel-out/ios-sim_arm64-min12.0-applebin_ios-ios_sim_arm64-dbg-ST-c2aefc9133a8/bin/_pch_output_dir/TestImports-App-Bridging-Header-swift_28IU2BV1DK30K-clang_1FNSWCOAS4SUQ.pch' for bridging header 'tests/ios/unit-test/test-imports-app/TestImports-App-Bridging-Header.h'
```
This is because this header was suppose to be an input to Swift compile via hmap creation rule. But in this breaking change …
> Pass compilation context via swift info in hmap creation due to rules_swift 2.1.1

- rules/framework.bzl
same idea as https://github.com/bazel-ios/rules_ios/pull/906 this time is for framework rule.
The CI error trying to fix in this PR is:
```
error: generate-pch command failed with exit code 1 (use -v to see invocation)
tests/ios/unit-test/test-imports-app/TestImports-App-Bridging-Header.h:1:9: error: 'TestImports-App/Header2.h' file not found
#import <TestImports-App/Header2.h>
^
1 error generated.
<unknown>:0: error: failed to emit precompiled header 'bazel-out/ios-sim_arm64-min12.0-applebin_ios-ios_sim_arm64-dbg-ST-c2aefc9133a8/bin/_pch_output_dir/TestImports-App-Bridging-Header-swift_28IU2BV1DK30K-clang_1FNSWCOAS4SUQ.pch' for bridging header 'tests/ios/unit-test/test-imports-app/TestImports-App-Bridging-Header.h'
2 errors generated.
error: fatalError
```
This time this header is …
> Pass compilation context via swift info in framework rule due to rules_swift 2.1.1

- rules/framework.bzl
- rules/hmap.bzl
This PR includes fixes for the following issues:
- Fixes the following issue with non-vfs on Bazel 7+:
```
<unknown>:0: error: module 'CustomModuleMap' was built in directory '/bazel-bin/tests/ios/frameworks/mixed-source/custom-module-map/CustomModuleMap/CustomModuleMap.framework' but now resides in directory '/bazel-bin/tests/ios/frameworks/mixed-source/custom-module-map/CustomModuleMap/CustomModuleMap.framework/Modules'
```
- Fixes the following issue in Bazel 6.5.0 with both vfs/non-vfs:
```
error: generate-pch command failed with exit code 1 (use -v to see invocation) tests/ios/unit-test/test-imports-app/TestImports-App-Bridging-Header.h:1:9: error: 'TestImports-App/Header2.h' file not found
#import <TestImports-App/Header2.h>
^
1 error generated.
<unknown>:0: error: failed to emit …
```
> Fix rules_swift 2 compatibility issues

- .github/workflows/tests.yml
- rules/import_middleman.bzl
- tests/ios/unit-test/test-imports-app/empty.swift
- tests/ios/unit-test/test-imports-app/main.m
What changed and why:
1. added test case that broke with main, under sandbox mode and bazel 7 and `arm64_simulator_use_device_deps` feature turned on :
To repro locally, run `bazel build //tests/ios/unit-test/test-imports-app:TestImports-App --config=ios --features apple.arm64_simulator_use_device_deps` and it fails. But success if change `.bazelversion` to 6.4.0
The error is "unable to find header `basic.h`" which is the same issue with what our own repo has. Also this only break Objc side not swift side (probably because CcInfo is more used by objc_library?)
2. To fix above: use the compilation_context generated originally.
The original fix https://github.com/bazel-ios/rules_ios/pull/873 is missing fields inside `compilation_context` such as `headers`. So might as well use the original …
> Fix import_middleman broken with Bazel 7 + sandbox mode

- rules/framework/vfs_overlay.bzl
hdrs, private_hdrs and swiftmodules of the same framework may be in different order when building with different build settings in Bazel 7. This change will ensure that the vfsoverlay file will be always the same for the same dependency graph.
> Ensures the determinism of vfsoverlay file

- .github/workflows/tests.yml
see https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs#example-only-cancel-in-progress-jobs-on-specific-branches
> Fix new PR cancel previous PR's workflow

- rules/framework.bzl
Rework of `_get_merged_swift_info` by bubble up the creation of clang module to `_apple_framework_packaging_impl` level, where it determine how to populate the clang module based on VFS feature on/off.
Remove the need to pass `virtualize_frameworks` flag to the private method `_get_merged_swift_info`
add `fail(swift_info.direct_modules)` after creation of it at the end of the packging impl method when running `bazel build //tests/ios/frameworks/testonly/... --config=ios --config=vfs`, you get 
```
[
struct(
clang = struct(compilation_context = <unknown object com.google.devtools.build.lib.rules.cpp.CcCompilationContext>, module_map = None, precompiled_module = None), compilation_context = None, is_system = False, name = "SwiftLibrary", 
swift = None),
struct(
clang = None, …
```
> Merge clang/swift modules into one `direct_module` in SwiftInfo for a framework

- rules/features.bzl
- rules/framework.bzl
already approved at https://github.com/bazel-ios/rules_ios/pull/917
Now it's about landing it in master and since it is guarded by a flag, it's no op unless you enable this feature
> Relanding of `Add swift.experimental_rules_swift_package_manager flag` back to master branch

- rules/framework.bzl
- rules/hmap.bzl
Last place that touched this code is on https://github.com/bazel-ios/rules_ios/pull/906where I thought it's important to construct SwiftInfo provider for hmap and add compilation context to pass the failing test. 
However that leads to a new [issue](https://github.com/bazel-ios/rules_ios/pull/916#pullrequestreview-2310552165) with `docc_archive` rule with latest `rules_apple/rules_swift`. We realized it's actually not needed to provide any SwiftInfo provider at all or it will "confuse" rules_swift/apple (since newer version starts to rely more on clang info from Swift info itself instead `apple_common.Objc`). Removing this also have the original failing test passing.
Tests done:
Will squash before merge as it contains already merged commits
> Remove swift info provider creation inside hmap rule

- rules/test.bzl
The `test.bzl` macros were incorrectly forwarding some of the attrs like `features`. This was leading to silent errors where things passed via `features` were dropped (such as main thread checking). This PR fixes the macro by properly forwarding ALL supported unit test attrs to the unit test rule.
> Fix unit test attr forwarding

- rules/library.bzl
- tests/ios/frameworks/bundle-in-data-resources/BUILD.bazel
- tests/ios/frameworks/bundle-in-data-resources/BundleInData.swift
- tests/ios/frameworks/bundle-in-data-resources/BundleInDataTests.swift
- tests/ios/frameworks/bundle-in-data-resources/fake-data.txt
This allows the wrap resource in filegroups and resource bundle generators to be disabled completely. It allows users to just pass in `data` and have the rule just forward that to the underlying libraries.
This cleans up the code a bit too since we use `data` directly instead of `module_data` which had to be converted into a list in a few places.
I added a test showcasing where this ability would be required. It fails without this change and passes when disabling the library tools
> Allow library tool resource handling to be disabled

- rules/framework.bzl
This is slow for very large targets and slows down `_apple_framework_packaging_impl`.
Before:
After:
> Avoid calling to_list in _get_cc_info_linker_inputs for performance

- rules/framework.bzl
This reverts commit 77c4afab96331d48138f090cd1e395f4db8bd644.
We're seeing some behavior changes in tests caused by this change. I haven't figured out the underlying issue yet, but I'm reverting this change until we can figure it out.
> Revert "Avoid calling to_list in _get_cc_info_linker_inputs for performance (#930)

- .bcr/presubmit.yml
- .github/workflows/tests.yml
- MODULE.bazel
- README.md
⚠️ Bazel 6 support is being dropped from rules_ios starting release > 5.3.0
With new changes in rules_apple such as removal of legacy objc_provider, latest rules_apple and latest rules_ios are no longer compatible, the PR is up to fix but we need to drop support for Bazel 6 to move on with that PR due to rules_apple dropping support for Bazel 6
Additionally, @luispadron 's survey showed most of us are on Bazel 7. 
- #934
> Drop support for Bazel 6

- rules/framework/vfs_overlay.bzl
Bazel 8 does not appear to support struct.to_json() anymore, so remove its usage in vfs_overlay. It appears this API has been around since at least 6.5 (https://bazel.build/versions/6.5.0/rules/lib/core/json), so changing to it shouldn't be an issue.
> Remove use of struct.to_json()

- rules/library.bzl
Allow `alwayslink` to be passed in `apple_framework` but set a default value to True so we handle errors as such
```sh
File "/Users/ssarad/.bazel_cache/output/external/BUILD.bazel", line 5, column 16, in <toplevel>
apple_framework(
File "/Users/ssarad/.bazel_cache/output/external/rules_ios~/rules/framework.bzl", line 98, column 28, in apple_framework
library = apple_library(
File "/Users/ssarad/.bazel_cache/output/external/rules_ios~/rules/library.bzl", line 1109, column 24, in apple_library
native.objc_library(
Error in objc_library: rule(...) got multiple values for parameter 'alwayslink'
```
> Handle multiple alwayslink error in objc_library

- MODULE.bazel
In https://github.com/bazelbuild/rules_swift/pull/1504 the index-import repository name was changed. rules_ios depends on the old name and thus breaks builds. It looks like these deps are unused (probably after we got rid of xcodeproj rules).
This fixes builds in rules_xcodeproj: https://github.com/MobileNativeFoundation/rules_xcodeproj/pull/3162
> Remove unused rules_swift repos

- .bcr/metadata.template.json
Trying to figure out why the release automation isn't publishing to BCR; current theory is we're missing a maintainer with a Github username, or the trailing comma in the maintainers list is a problem. Whatever the case, add me 😄
> Add Jonathan Schear as a maintainer
